### ISSUE TITLE
Trouble running on GPU

### ISSUE THREAD

**Issue by molleraj** [nanoporetech/bonito#111]
Hi all, I am trying to run bonito to basecall ~12 datasets on a GPU server, but bonito is not detecting the NVIDIA GPU driver.
This is the error I get:

```console
[molleraj@gpu016 ~]$ module load cuda
[molleraj@gpu016 ~]$ bonito basecaller dna_r9.4.1 ~/pylon_nanopore_reads/DNA_mix/N384_parent_amplicon > ~/pylon_nanopore_reads/DNA_mix/N384_parent_amplicon.fasta &
[1] 28280
[molleraj@gpu016 ~]$ > loading model
Traceback (most recent call last):
  File "/home/molleraj/bonito/venv3/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito', 'console_scripts', 'bonito')()
  File "/home/molleraj/bonito/bonito/__init__.py", line 39, in main
    args.func(args)
  File "/home/molleraj/bonito/bonito/cli/basecaller.py", line 26, in main
    model = load_model(args.model_directory, args.device, weights=int(args.weights))
  File "/home/molleraj/bonito/bonito/util.py", line 288, in load_model
    state_dict = torch.load(weights, map_location=device)
  File "/home/molleraj/bonito/venv3/lib64/python3.6/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/molleraj/bonito/venv3/lib64/python3.6/site-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
  File "/home/molleraj/bonito/venv3/lib64/python3.6/site-packages/torch/serialization.py", line 729, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/molleraj/bonito/venv3/lib64/python3.6/site-packages/torch/serialization.py", line 811, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/home/molleraj/bonito/venv3/lib64/python3.6/site-packages/torch/serialization.py", line 178, in default_restore_location
    result = fn(storage, location)
  File "/home/molleraj/bonito/venv3/lib64/python3.6/site-packages/torch/serialization.py", line 154, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/molleraj/bonito/venv3/lib64/python3.6/site-packages/torch/serialization.py", line 135, in validate_cuda_device
    device = torch.cuda._utils._get_device_index(location, True)
  File "/home/molleraj/bonito/venv3/lib64/python3.6/site-packages/torch/cuda/_utils.py", line 31, in _get_device_index
    return torch.cuda.current_device()
  File "/home/molleraj/bonito/venv3/lib64/python3.6/site-packages/torch/cuda/__init__.py", line 330, in current_device
    _lazy_init()
  File "/home/molleraj/bonito/venv3/lib64/python3.6/site-packages/torch/cuda/__init__.py", line 149, in _lazy_init
    _check_driver()
  File "/home/molleraj/bonito/venv3/lib64/python3.6/site-packages/torch/cuda/__init__.py", line 54, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError:
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

[1]+  Exit 1                  bonito basecaller dna_r9.4.1 ~/pylon_nanopore_reads/DNA_mix/N384_parent_amplicon > ~/pylon_nanopore_reads/DNA_mix/N384_parent_amplicon.fasta</tt>
[molleraj@gpu016 ~]$ exit
```

As you can see (module load cuda), I loaded CUDA (10.2) libraries before running. This is the output of nvidia-smi:

```console
[molleraj@gpu016 ~]$ nvidia-smi
Mon Feb  1 16:39:17 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: ERR!     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:83:00.0 Off |                    0 |
| N/A   32C    P8    27W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 00000000:84:00.0 Off |                    0 |
| N/A   31C    P8    31W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 00000000:8A:00.0 Off |                    0 |
| N/A   34C    P8    25W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 00000000:8B:00.0 Off |                    0 |
| N/A   33C    P8    33W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Any help would be greatly appreciated!

Thanks,
Jon

**Comment by iiSeymour** [comment]
Hey @molleraj 

What sticks out to me is `nvidia-smi` is reporting `CUDA Version: ERR!` are you sure you have a CUDA SDK installed?

**Comment by molleraj** [comment]
> What sticks out to me is `nvidia-smi` is reporting `CUDA Version: ERR!` are you sure you have a CUDA SDK installed?

Thanks @iiSeymour. How would I tell?

**Comment by molleraj** [comment]
This is running on a CentOS GPU cluster for reference.

**Comment by iiSeymour** [comment]
Hard for me to say as your cluster might be set up in a specific way - do you have support contact for the cluster you can use?

**Comment by molleraj** [comment]
I have contacted the support for the cluster I can use, but he said to post an issue here. Maybe I can ask about the CUDA Version: ERR! message.

**Comment by iiSeymour** [comment]
I've never seen `CUDA Version: ERR` reported myself but maybe @sirelkhatim or @EpiSlim can help.

**Comment by EpiSlim** [comment]
I see one of two possibilities: 

1. `PATH` and/or `LD_LIBRARY_PATH` are not correctly set up for cuda
2. This is a cluster with multiple nodes and you need to submit your job in a certain way (probably from the parent node) to access the CUDA driver.

**Comment by molleraj** [comment]
Thanks @EpiSlim.

> I see one of two possibilities:
> 
>     1. `PATH` and/or `LD_LIBRARY_PATH` are not correctly set up for cuda

I can try posting those shortly.

>     2. This is a cluster with multiple nodes and you need to submit your job in a certain way (probably from the parent node) to access the CUDA driver.

It is a cluster with multiple nodes. How do I submit the job to access the CUDA driver? Is this truly the case when nvidia-smi works?

**Comment by molleraj** [comment]
OK, so here is the PATH and LD_LIBRARY_PATH on the cluster. I will ask the cluster help desk your second question.

```console
(venv3) [molleraj@login018 ~]$ interact -p GPU --gres=gpu:k80:4

A command prompt will appear when your session begins
"Ctrl+d" or "exit" will end your session

srun: job 12706781 queued and waiting for resources

srun: job 12706781 has been allocated resources

[molleraj@gpu016 ~]$
[molleraj@gpu016 ~]$ echo $LD_LIBRARY_PATH
/opt/packages/cuda/10.2/lib64:/home/molleraj/bonito/venv3/lib64/:/home/molleraj/bonito/venv3/lib/:/opt/intel/itac/2020.3.036/intel64/slib:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/libfabric/lib:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/release:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib:/opt/intel/compilers_and_libraries_2020.4.304/linux/ipp/lib/intel64:/opt/intel/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.4.304/linux/tbb/lib/intel64/gcc4.8:/opt/intel/debugger_2020/libipt/intel64/lib:/opt/intel/compilers_and_libraries_2020.4.304/linux/daal/lib/intel64_lin
[molleraj@gpu016 ~]$ echo $PATH
/opt/packages/xdusage/2.1-1/bin:/opt/packages/cuda/10.2/bin:/home/molleraj/bonito/venv3/bin:/usr/lib64/qt-3.3/bin:/opt/intel/advisor_2020.3.0.607294/bin64:/opt/intel/vtune_amplifier_2019.6.0.602217/bin64:/opt/intel/inspector_2020.3.0.604771/bin64:/opt/intel/itac/2020.3.036/intel64/bin:/opt/intel/clck/2019.5/bin/intel64:/opt/intel/compilers_and_libraries_2020.4.304/linux/bin/intel64:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/libfabric/bin:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin:/opt/intel/debugger_2020/gdb/intel64/bin:/opt/packages/slurm/default/bin:/opt/packages/allocations:/opt/packages/interact/bin:/usr/lib64/ccache:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/puppet/bin:/opt/intel/parallel_studio_xe_2020.4.912/bin:/bin:/sbin:/opt/puppetlabs/bin:/home/molleraj/.local/bin:/home/molleraj/bin:/opt/puppetlabs/puppet/bin:/bin:/sbin:/opt/puppetlabs/puppet/bin:/bin:/sbin
[molleraj@gpu016 ~]$
```

**Comment by molleraj** [comment]
Hi all, I finally tracked down the issue. I was seeing CUDA Version: ERR! with screen open and CUDA Version: 11.2 with screen shut down. I think I will look further into this issue for my own knowledge. Bonito works perfectly now!! Thanks for all your help!
