### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by visanuwan** [nanoporetech/bonito#125]
I have an issue using the pre-prepared dataset from the command provided in the README.md

```
$ bonito download --training
$ bonito train --amp /data/training/model-dir
```
I have successfully downloaded the dna_r9.4.1.hdf5
However, I got an error after running the second command.
Could you please guide me? The error message is as follows:

```
(venv3) c1701:visanu:~/tools/bonito/bonito$ bonito train --amp test_train
[loading data]
Traceback (most recent call last):
  File "/scrfs/storage/visanu/home/tools/bonito/venv3/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito', 'console_scripts', 'bonito')()
  File "/scrfs/storage/visanu/home/tools/bonito/bonito/__init__.py", line 39, in main
    args.func(args)
  File "/scrfs/storage/visanu/home/tools/bonito/bonito/cli/train.py", line 36, in main
    train_data = load_data(limit=args.chunks, directory=args.directory)
  File "/scrfs/storage/visanu/home/tools/bonito/bonito/util.py", line 220, in load_data
    chunks = np.load(os.path.join(directory, "chunks.npy"), mmap_mode='r')
  File "/scrfs/storage/visanu/home/tools/bonito/venv3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/scrfs/storage/visanu/home/tools/bonito/bonito/data/dna_r9.4.1/chunks.npy'
```

**Comment by iiSeymour** [comment]
Hey @visanuwan 

You can specify the location of the training data with `--directory` 

```
$ bonito train --amp /data/training/model-dir --directory /data/training/training-data-dir
```

**Comment by davidnewman02** [comment]
Closing as issue has been resolved
