### ISSUE TITLE
CUDA out of memory error in bonito train

### ISSUE THREAD

**Issue by rfinkers** [nanoporetech/bonito#128]
try to run: `bonito train --amp --directory ctc-data model-dir`

But run into the following error:

[loading data]
[validation set not found: splitting training set]
[loading model]
[0/881405]:   0%|                                                                          | [00:00]
Traceback (most recent call last):
  File "/home/finke002/anaconda3/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito==0.3.6', 'console_scripts', 'bonito')())
  File "/home/finke002/anaconda3/lib/python3.8/site-packages/bonito/__init__.py", line 39, in main
    args.func(args)
  File "/home/finke002/anaconda3/lib/python3.8/site-packages/bonito/cli/train.py", line 89, in main
    train_loss, duration = train(
  File "/home/finke002/anaconda3/lib/python3.8/site-packages/bonito/training.py", line 197, in train
    log_probs = model(data.to(device))
  File "/home/finke002/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/finke002/anaconda3/lib/python3.8/site-packages/bonito/crf/model.py", line 33, in forward
    return self.global_norm(self.encoder(x))
  File "/home/finke002/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/finke002/anaconda3/lib/python3.8/site-packages/bonito/crf/model.py", line 94, in forward
    return (scores - self.seq_dist.logZ(scores)[:, None] / len(scores)).to(x.dtype)
RuntimeError: CUDA out of memory. Tried to allocate 500.00 MiB (GPU 0; 7.79 GiB total capacity; 6.80 GiB already allocated; 129.19 MiB free; 6.85 GiB reserved in total by PyTorch)

**Comment by iiSeymour** [comment]
Hey @rfinkers 

To reduce the required memory you can decrease the batch size from 64 to say 48 or 32:

```
$ bonito train --batch 48 --amp --directory ctc-data model-dir
```
