### ISSUE TITLE
conda + pip install - help needed

### ISSUE THREAD

**Issue by splaisan** [nanoporetech/bonito#132]
I work with conda on my machine rather than with virt env's.

Could someone please help me get the right conda environment.yaml to install bonito with GPU support

So far I tried as shown below but bonito does not start well after activating the resulting env. Should I use a specific version of python?

Thanks in advance

conda env create -n bonito --file environment.yaml

with environment.yaml:

```
channels:
    - conda-forge
    - bioconda
dependencies:
    - pip==20.3.4
    - mappy==2.17
    - toml==0.10.0
    - tqdm==4.31.1
    - numpy<=1.18.5
    - optuna==1.1.0
    - pandas>=0.24.2
    - requests==2.22.0
    - ont-fast5-api==3.1.6
    - pip:
        - crf-beam==0.0.1a0
        - fast-ctc-decode==0.2.5
        - torch>=1.1.0,<=1.5
        - seqdist==0.0.3
       - ont-bonito

#bonito-cuda-runtime==0.0.2a2
#pyclaragenomics-cuda-10-0==0.4.2
```

```
$ bonito basecaller --help
Traceback (most recent call last):
  File "/opt/miniconda3/envs/bonito/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito==0.3.6', 'console_scripts', 'bonito')())
  File "/opt/miniconda3/envs/bonito/bin/bonito", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/miniconda3/envs/bonito/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/opt/miniconda3/envs/bonito/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/__init__.py", line 3, in <module>
    from bonito.cli import basecaller, evaluate, view, convert, download, pair
  File "/opt/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/cli/basecaller.py", line 16, in <module>
    from bonito.fast5 import get_reads, read_chunks
  File "/opt/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/fast5.py", line 13, in <module>
    from scipy.signal import find_peaks
  File "/opt/miniconda3/envs/bonito/lib/python3.8/site-packages/scipy/signal/__init__.py", line 292, in <module>
    from . import sigtools, windows
  File "/opt/miniconda3/envs/bonito/lib/python3.8/site-packages/scipy/signal/windows/__init__.py", line 41, in <module>
    from .windows import *
  File "/opt/miniconda3/envs/bonito/lib/python3.8/site-packages/scipy/signal/windows/windows.py", line 7, in <module>
    from scipy import linalg, special, fft as sp_fft
  File "/opt/miniconda3/envs/bonito/lib/python3.8/site-packages/scipy/fft/__init__.py", line 79, in <module>
    from ._helper import next_fast_len
  File "/opt/miniconda3/envs/bonito/lib/python3.8/site-packages/scipy/fft/_helper.py", line 3, in <module>
    from ._pocketfft import helper as _helper
  File "/opt/miniconda3/envs/bonito/lib/python3.8/site-packages/scipy/fft/_pocketfft/__init__.py", line 3, in <module>
    from .basic import *
  File "/opt/miniconda3/envs/bonito/lib/python3.8/site-packages/scipy/fft/_pocketfft/basic.py", line 6, in <module>
    from . import pypocketfft as pfft
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /opt/miniconda3/envs/bonito/lib/python3.8/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-38-x86_64-linux-gnu.so)
```

**Comment by iiSeymour** [comment]
Hey @splaisan 

This looks like a problem with `scipy`, `conda` and your environment. You could try this https://stackoverflow.com/questions/48453497/anaconda-libstdc-so-6-version-glibcxx-3-4-20-not-found

HTH

**Comment by splaisan** [comment]
> Hey @splaisan
> 
> This looks like a problem with `scipy`, `conda` and your environment. You could try this https://stackoverflow.com/questions/48453497/anaconda-libstdc-so-6-version-glibcxx-3-4-20-not-found
> 
> HTH

Thanks but this did not help, I then tried to create an empty conda env and install with pip only which also fails with version conflicts for torch and fast-ctc-decode for which available versions are too high.

Is there a max python version compatible with ont-bonito?

**Comment by iiSeymour** [comment]
You will need `torch==1.5` and `fast-ctc-decode` provides builds for `py3.{5,6,7,8}` https://pypi.org/project/fast-ctc-decode/0.2.5/#files

**Comment by splaisan** [comment]
Thanks Chris,
It finally seemed to work by choosing python 3.6 (I had 3.9 installed automatically before) and doing the following:

conda create -n bonito python=3.6
conda activate bonito
git clone https://github.com/nanoporetech/bonito.git
cd bonito
pip install -r requirement.txt
python setup.py develop
bonito download --models --latest

# test
TBD, large test data download on the way


I wish I could have used conda instead of pip but nevermind, these version conflicts are just too much for my level.

**Comment by iiSeymour** [comment]
Good to hear @splaisan!

**Comment by mbhall88** [comment]
For anyone else who lands here, the following environment file should install the latest bonito into a conda environment. Handy if you're using bonito in a snakemake pipeline

```yaml
name: bonito_0_5_3
channels:
    - conda-forge
dependencies:
    - python=3.9
    - pip
    - cudatoolkit=11.3
    - pip:
        - --find-links https://download.pytorch.org/whl/torch_stable.html
        - ont-bonito-cuda113==0.5.3
```

You can install this into a new conda (or mamba) environment using `conda env create -f environment.yaml`
