### ISSUE TITLE
Issue downloading training data set

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/bonito#134]
I cannot download training data but downloading models are no problem.

Is this caused by the fact I install bonito within a conda environment? 

```
(bonito) callum@dgt-gpu2:~$ bonito download --all --force
[downloading models]
[downloaded dna_r9.4.1@v1.zip]                                                                      
[downloaded dna_r9.4.1@v2.zip]                                                                      
[downloaded dna_r9.4.1@v3.zip]                                                                      
[downloaded dna_r9.4.1@v3.1.zip]                                                                    
[downloaded dna_r9.4.1@v3.2.zip]                                                                    
[downloaded dna_r9.4.1.zip]                                                                         
[downloaded dna_r10.3_q20ea.zip]                                                                    
[downloaded dna_r10.3@v3.zip]                                                                       
[downloaded dna_r10.3@v3.2.zip]                                                                     
[downloaded dna_r10.3.zip]                                                                          
[downloading training data]
Traceback (most recent call last):
  File "/home/callum/miniconda3/envs/bonito/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/home/callum/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/__init__.py", line 39, in main
    args.func(args)
  File "/home/callum/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/cli/download.py", line 114, in main
    File(__models__, train, args.force).download()
  File "/home/callum/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/cli/download.py", line 52, in download
    rmtree(self.location(fname.strip('.zip')))
  File "/home/callum/miniconda3/envs/bonito/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/callum/miniconda3/envs/bonito/lib/python3.8/shutil.py", line 628, in _rmtree_safe_fd
    onerror(os.scandir, path, sys.exc_info())
  File "/home/callum/miniconda3/envs/bonito/lib/python3.8/shutil.py", line 624, in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:
NotADirectoryError: [Errno 20] Not a directory: '/home/callum/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/models/dna_r9.4.1.hdf5'
```

**Comment by iiSeymour** [comment]
This is a bug with downloading the training data when using `--force`. I will get this fixed but you can download the training data with `bonito download --training` for now.

**Comment by callumparr** [comment]
Hey thank you for quick reply: 

I used `bonito download --training`

It tells me that its skipping because I guess I already have it? 

```
[downloading training data]
[skipping dna_r9.4.1.hdf5]
```

Can confirm that the this hdf5 file is in bonito repository. 

```
find . -name dna_r9.4.1.hdf5 
/home/callum/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/models/dna_r9.4.1.hdf5
```

If I run `bonito train test` or 

```
bonito train test --directory /home/callum/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/models/dna_r9.4.1.hdf5
```
Get this error:

```
[loading data]
Traceback (most recent call last):
  File "/home/callum/miniconda3/envs/bonito/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/home/callum/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/__init__.py", line 39, in main
    args.func(args)
  File "/home/callum/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/cli/train.py", line 36, in main
    train_data = load_data(limit=args.chunks, directory=args.directory)
  File "/home/callum/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/util.py", line 220, in load_data
    chunks = np.load(os.path.join(directory, "chunks.npy"), mmap_mode='r')
  File "/home/callum/miniconda3/envs/bonito/lib/python3.8/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/callum/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/models/chunks.npy'
```

**Comment by iiSeymour** [comment]
The hdf5 training file gets converted after downloading. You should have a `dna_r9.4.1` directory next to the file, if you don't you can run a conversion before training.

```
$ bonito convert /home/callum/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/models/dna_r9.4.1.hdf5 /home/callum/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/models/dna_r9.4.1
$ bonito train test --directory /home/callum/miniconda3/envs/bonito/lib/python3.8/site-packages/bonito/models/dna_r9.4.1

```

**Comment by callumparr** [comment]
Thank you I could run the test training now.
