### ISSUE TITLE
pair calling ValueError

### ISSUE THREAD

**Issue by Psy-Fer** [nanoporetech/bonito#142]
Hello,

I'm trying to use bonito pair with the following command

`bonito pair dna_r9.4.1 dna_r9.4.1 pairs.csv ./data --sep ' ' > output.fasta`

However I am getting the following error:

```
Process PairDecoderWriter-9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/install/bonito/bonito/cli/pair.py", line 155, in run
    temp_seq, temp_path = beam_search(
ValueError: alphabet size 5 does not match probability matrix inner dimension 5120
```
Am I doing something wrong?

The data folder comprises of 2 single read fast5 files (which basecall fine with `bonito basecaller` )

pairs contains the associated readIDs separated by a space.

Any pointers is appreciated.

James

**Comment by iiSeymour** [comment]
Hey @Psy-Fer 

You are not doing anything wrong here - `bonito pair` hasn't been updated to work with the latest crf models so the simplest thing you can do for now is to grab version `0.2.3`. 

Updates are coming for this in the next release.

**Comment by Psy-Fer** [comment]
Oh excxellent!

Thanks for that. I'll look out for the next release.

Cheers

**Comment by Psy-Fer** [comment]
G'day Chris,

Was I've tried again with the new release, but same error. Did this end up makinging it into the release in the end?

Cheers,
James

**Comment by Psy-Fer** [comment]
Cheers  @iiSeymour
Running this on our Q20ea data to see what happens to the modal line...
