### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by jagos01** [nanoporetech/bonito#146]
Hello,
I am having an issue when basecalling with bonito v0.3.6.  My setup is as follows: 
Ubuntu 18.04
RTX 2080ti
Cuda 10.1 and cuDNN 7.6.4 

When installing bonito I edited seqdist settings.ini for cupy-cuda101 as suggested in #60. The following error is returned when trying to basecall:
$ bonito basecaller dna_r9.4.1 test_fast5_folder > test.fasta
> loading model
Traceback (most recent call last):
  File "/home/DRD/bonito/bonito_venv/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito', 'console_scripts', 'bonito')())
  File "/home/DRD/bonito/bonito/__init__.py", line 39, in main
    args.func(args)
  File "/home/DRD/bonito/bonito/cli/basecaller.py", line 28, in main
    model = load_model(args.model_directory, args.device, weights=int(args.weights))
  File "/home/DRD/bonito/bonito/util.py", line 314, in load_model
    model.to(device)
  File "/home/DRD/bonito/bonito_venv/lib/python3.6/site-packages/torch-1.8.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/home/DRD/bonito/bonito_venv/lib/python3.6/site-packages/torch-1.8.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/DRD/bonito/bonito_venv/lib/python3.6/site-packages/torch-1.8.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/DRD/bonito/bonito_venv/lib/python3.6/site-packages/torch-1.8.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/DRD/bonito/bonito_venv/lib/python3.6/site-packages/torch-1.8.0-py3.6-linux-x86_64.egg/torch/nn/modules/rnn.py", line 186, in _apply
    self.flatten_parameters()
  File "/home/DRD/bonito/bonito_venv/lib/python3.6/site-packages/torch-1.8.0-py3.6-linux-x86_64.egg/torch/nn/modules/rnn.py", line 176, in flatten_parameters
    self.batch_first, bool(self.bidirectional))  # type: ignore
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

Do you have any ideas how to resolve this?
Thanks,
Scott

**Comment by iiSeymour** [comment]
Hey @jagos01 

Did you also install a build of PyTorch that uses Cuda 10.1 as the default builds on PyPI are built against Cuda 10.2.

**Comment by jagos01** [comment]
I installed PyTorch 1.7.1 for Cuda 10.1 and now have v0.3.8 running.  One more question, is bonito_medaka_0.3.1.hdf5 the latest model for Medaka and is it compatilbe with Bonito v0.3.8?
Thanks,
Scott

**Comment by GeoMicroSoares** [comment]
Hey @iiSeymour I'm getting the same error as posted here. Can you specify how exactly you'd 
> install a build of PyTorch that uses Cuda 10.1

Using `pip3 install torch==1.7.0` for example I get 
```
...
pkg_resources.DistributionNotFound: The 'torch==1.8.0' distribution was not found and is required by ont-bonito
```

**Comment by libenping** [comment]
Hello,my setup is as follows:
Ubuntu18.04.1
cuda 10.2 
torch 1.8.0
and when print(torch.backends.cudnn.version()),the result is 7605,so I think cuDNN is 7.6.05.
When installing the bonito V0.3.8, everything is OK。 However when basecalling ONT data,it return error as follows:
$ bonito basecaller /home/prom/software/bonito/bonito_20210508/bonito/bonito/models/dna_r9.4.1/  ~/software/basecalling/20210506_bacteria_data/   > basecalls.fasta
`> loading model
Traceback (most recent call last):
  File "/home/prom/software/bonito/bonito_20210508/bonito/venv3/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito', 'console_scripts', 'bonito')()
  File "/home/prom/software/bonito/bonito_20210508/bonito/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/prom/software/bonito/bonito_20210508/bonito/bonito/cli/basecaller.py", line 28, in main
    model = load_model(args.model_directory, args.device, weights=int(args.weights))
  File "/home/prom/software/bonito/bonito_20210508/bonito/bonito/util.py", line 314, in load_model
    model.to(device)
  File "/home/prom/software/bonito/bonito_20210508/bonito/venv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/home/prom/software/bonito/bonito_20210508/bonito/venv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/prom/software/bonito/bonito_20210508/bonito/venv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/prom/software/bonito/bonito_20210508/bonito/venv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/prom/software/bonito/bonito_20210508/bonito/venv3/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 186, in _apply
    self.flatten_parameters()
  File "/home/prom/software/bonito/bonito_20210508/bonito/venv3/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 172, in flatten_parameters
    torch._cudnn_rnn_flatten_weight(
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
`
So can you give me some suggestion about this problem? Thank you!
By the way, Bonito V0.3.6 can work well.

**Comment by dbernick** [comment]
It seems there is a circular dependency that is causing grief.
torch 1.8.0 is not playing with cu102 - produces CUDNN_STATUS_NOT_INITIALIZE.
cuda 10.2 is  required by seqDist.
not-bonito 0.3.7 requires torch 1.8.0

how do we fix this?

**Comment by iiSeymour** [comment]
Cupy/seqdist is no longer required as of v0.5.1.
