### ISSUE TITLE
kbeam import error

### ISSUE THREAD

**Issue by helix-phoenix** [nanoporetech/bonito#152]
Hello,

I'm trying to run bonito basecaller on Nvidia Jetson Nano, however, i'm experiencing a kbeam ImportError.

--------
> loading model
Traceback (most recent call last):
  File "/home/helix/bonito/venv3/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito', 'console_scripts', 'bonito')())
  File "/home/helix/bonito/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/helix/bonito/bonito/cli/basecaller.py", line 28, in main
    model = load_model(args.model_directory, args.device, weights=int(args.weights))
  File "/home/helix/bonito/bonito/util.py", line 297, in load_model
    Model = load_symbol(config, "Model")
  File "/home/helix/bonito/bonito/util.py", line 264, in load_symbol
    imported = import_module(config['model']['package'])
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/helix/bonito/bonito/crf/__init__.py", line 2, in <module>
    from .basecall import basecall
  File "/home/helix/bonito/bonito/crf/basecall.py", line 7, in <module>
    from kbeam import beamsearch
  File "/home/helix/bonito/venv3/lib/python3.6/site-packages/kbeam/__init__.py", line 1, in <module>
    from .kbeam import *
ImportError: /home/helix/bonito/venv3/lib/python3.6/site-packages/kbeam/kbeam.cpython-36m-aarch64-linux-gnu.so: undefined symbol: PyFPE_jbuf
-------
FYI, I'm using Python 3.6.9 on Ubuntu 18.04 & crf_beam wheel from #80  

Thank you!

**Comment by iiSeymour** [comment]
Hey @helix-phoenix 

Unfortunately, PyPI doesn't support prebuilt packages for `aarch64`.
