### ISSUE TITLE
Duplex Reads Error

### ISSUE THREAD

**Issue by mattdmem** [nanoporetech/bonito#159]
Hello,

Just trying out bonito v0.4.0 duplex calling, however I get this message:

```
> loading model
> loading reference
> finding follow on strands
Traceback (most recent call last):
  File "/home/md1mpar/miniconda3/envs/bonito-0.4/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/home/md1mpar/miniconda3/envs/bonito-0.4/lib/python3.7/site-packages/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/md1mpar/miniconda3/envs/bonito-0.4/lib/python3.7/site-packages/bonito/cli/duplex.py", line 348, in main
    pairs = find_follow_on(pairs)
  File "/home/md1mpar/miniconda3/envs/bonito-0.4/lib/python3.7/site-packages/bonito/cli/duplex.py", line 214, in find_follow_on
    return df[mask]
  File "/home/md1mpar/miniconda3/envs/bonito-0.4/lib/python3.7/site-packages/pandas/core/frame.py", line 2897, in __getitem__
    return self._getitem_bool_array(key)
  File "/home/md1mpar/miniconda3/envs/bonito-0.4/lib/python3.7/site-packages/pandas/core/frame.py", line 2944, in _getitem_bool_array
    f"Item wrong length {len(key)} instead of {len(self.index)}."
ValueError: Item wrong length 1 instead of 0.
```

I am using the alignment mode, so I quickly recalled my data with guppy 5 on fast mode with `-a` set to get a sequencing summary with alignment details.

`bonito duplex dna_r9.4.1  guppy-5.0.7-fast/workspace --summary guppy-5.0.7-fast/sequencing_summary.txt --reference reference/hg38.mmi > bonito-0.4.0-duplex/basecalls.sam`

Thanks!

**Comment by iiSeymour** [comment]
Hey @mattdmem 

I've not hit that one before and it's not obvious what has happened from the traceback - can you share the alignment summary file?

**Comment by mattdmem** [comment]
Hey!

Sure - can I share outside of github? email?

**Comment by mattdmem** [comment]
here is the head
```
filename        read_id run_id  batch_id        channel mux     start_time      duration        num_events      passes_filtering        template_start  num_events_template     template_duration       sequence_length_template        mean_qscore_template    strand_score_template   median_template mad_template    scaling_median_template scaling_mad_template    alignment_genome        alignment_direction     alignment_genome_start alignment_genome_end     alignment_strand_start  alignment_strand_end    alignment_num_insertions        alignment_num_deletions alignment_num_aligned   alignment_num_correct   alignment_identity      alignment_accuracy      alignment_score alignment_coverage
FAP17584_fail_794336d8_24.fast5 3f334c57-ee52-47ec-ad5f-69ddf61205af    794336d80d15048dabe15fb17a9f94675c75e8e5        0       490     4       74258.745000    18.925250       15140   FALSE   74258.745000    15140  18.925250        7832    7.716190        2.911889        120.326904      10.794031       120.326904      10.794031       chr13   +       54032813        54037257        82      4520    120     126     4318    4196   0.971746 0.919369        6776    0.551328
FAP17584_fail_794336d8_24.fast5 d666c249-3634-42d5-8933-5269bc6e8634    794336d80d15048dabe15fb17a9f94675c75e8e5        0       45      2       75395.303250    9.499750        7599    FALSE   75396.268250    6827   8.534750 3297    5.402882        2.681613        63.879433       6.016346        63.879433       6.016346        *       *       -1      -1      -1      -1      -1      -1      -1      -1      -1.000000       -1.000000       -1      -1.000000
FAP17584_fail_794336d8_24.fast5 69f98678-22a1-4053-a3cf-98f74d441c1b    794336d80d15048dabe15fb17a9f94675c75e8e5        0       88      1       73253.100000    2.616500        2093    FALSE   73253.100000    2093   2.616500 583     4.236988        2.362819        72.903946       1.769513        72.903946       1.769513        chr22   +       47379108        47379335        1       220     10      18      209     187     0.894737
        0.789030        186     0.358491
FAP17584_fail_794336d8_24.fast5 4c233938-1f35-4209-adaf-5e22074b293e    794336d80d15048dabe15fb17a9f94675c75e8e5        0       264     1       79235.124250    35.573750       28459   FALSE   79235.220500    28382  35.477500        12167   5.461009        2.607468        87.767860       10.970983       87.767860       10.970983       *       *       -1      -1      -1      -1      -1      -1      -1      -1      -1.000000      -1.000000        -1      -1.000000
FAP17584_fail_794336d8_24.fast5 c6e059b6-61d0-413c-86b6-c52799f85d01    794336d80d15048dabe15fb17a9f94675c75e8e5        0       118     3       77467.601000    25.467000       20373   FALSE   77467.634750    20346  25.433250        11697   5.719073        2.900024        99.092751       7.962810        99.092751       7.962810        chr12   +       71612266        71616919        27      4376    145     449     4204    3784   0.900095 0.788662        3376    0.359408
FAP17584_fail_794336d8_24.fast5 6d86e99a-bb43-4e7d-9065-6d6f9b87a754    794336d80d15048dabe15fb17a9f94675c75e8e5        0       319     2       79160.087500    22.820000       18256   FALSE   79160.241250    18133  22.666250        8084    5.048975        2.631778        72.196144       8.493664        72.196144       8.493664        *       *       -1      -1      -1      -1      -1      -1      -1      -1      -1.000000      -1.000000        -1      -1.000000
FAP17584_fail_794336d8_24.fast5 4c05fc59-7b62-4146-90f9-437dbc280e11    794336d80d15048dabe15fb17a9f94675c75e8e5        0       335     4       78437.608750    1.498750        1199    FALSE   78437.608750    1199   1.498750 530     5.826710        2.587940        125.812401      11.501837       125.812401      11.501837       chr7    +       30243186        30243453        273     530     3       13      254     250     0.984252
        0.925926        404     0.479245
FAP17584_fail_794336d8_24.fast5 b2ef3f59-f564-44ab-a27b-fe97c6f7675d    794336d80d15048dabe15fb17a9f94675c75e8e5        0       493     3       78985.946000    3.226250        2581    FALSE   78986.038500    2507   3.133750 1010    5.587069        2.599144        66.533699       6.901102        66.533699       6.901102        *       *       -1      -1      -1      -1      -1      -1      -1      -1      -1.000000       -1.000000       -1      -1.000000
FAP17584_fail_794336d8_24.fast5 47e2c54f-cae2-428d-be8a-c57ea7c744a8    794336d80d15048dabe15fb17a9f94675c75e8e5        0       266     3       73005.976500    32.908500       26326   FALSE   73006.077750    26245  32.807250        13099   3.641129        2.593385        63.702480       4.777686        63.702480       4.777686        *       *       -1      -1      -1      -1      -1      -1      -1      -1      -1.000000      -1.000000        -1      -1.00000
```

**Comment by iiSeymour** [comment]
You can upload [here](https://nanoporetech.ent.box.com/f/7c4375e2b71b48258ebed29f198b89ab)

**Comment by mattdmem** [comment]
done!

**Comment by iiSeymour** [comment]
When running just the `find_follow_on` snippet below on your sequencing summary I find a small number of pairs.

```python
import sys
import numpy as np
import pandas as pd


def find_follow_on(df, gap=5, distance=51, cov=0.85, min_len=100):
    """
    Find follow on reads from a sequencing summary file.
    """
    df = df[
        df.alignment_coverage.astype('float32').gt(cov) &
        df.sequence_length_template.astype('int32').gt(min_len)
    ]
    df = df.sort_values(['run_id', 'channel', 'mux', 'start_time'])

    genome_start = np.array(df.alignment_genome_start, dtype=np.int32)
    genome_end = np.array(df.alignment_genome_end, dtype=np.int32)
    direction = np.array(df.alignment_direction)
    start_time = np.array(df.start_time, dtype=np.float32)
    end_time = np.array(df.start_time + df.duration, dtype=np.float32)
    channel = np.array(df.channel, dtype=np.int32)
    mux = np.array(df.mux, dtype=np.int32)

    filt = (
        (channel[1:] == channel[:-1]) &
        (mux[1:] == mux[:-1]) &
        (np.abs(genome_start[1:] - genome_start[:-1]) < distance) &
        (np.abs(genome_end[1:] - genome_end[:-1]) < distance) &
        (direction[1:] != direction[:-1]) &
        (start_time[1:] - end_time[:-1] < gap)
    )
    mask = np.full(len(filt) + 1, False)
    mask[:-1] = mask[:-1] | filt
    mask[1:] = mask[1:] | filt

    return df[mask]


if __name__ == "__main__":
    pairs = pd.read_csv(sys.argv[1], sep='\t')
    pairs = pairs[pairs.sequence_length_template.gt(0)]
    if 'filename' in pairs.columns:
        pairs = pairs.rename(columns={'filename': 'filename_fast5'})
    if 'alignment_strand_coverage' in pairs.columns:
        pairs = pairs.rename(columns={'alignment_strand_coverage': 'alignment_coverage'})

    print("total records", len(pairs))
    pairs = find_follow_on(pairs)
    print("pairs found", len(pairs))
```

I can reproduce the traceback by passing an empty `DataFrame` to `find_follow_on` which points to the issue being the check on [duplex.py#L343](https://github.com/nanoporetech/bonito/blob/master/bonito/cli/duplex.py#L343). This suggests that the fast5 files listed in the sequencing summary are not found in `guppy-5.0.7-fast/workspace` *(perhaps in a subdirectory?)*.

**Comment by mattdmem** [comment]
ok yes - sorry about that - I wrongly assumed it would look recursively! It's working now. Thanks!
