### ISSUE TITLE
CUDA memory allocate error

### ISSUE THREAD

**Issue by gushiro** [nanoporetech/bonito#182]
Hi there,

I cannot avoid the memory error I have despite changing the chunksize and batch parameters. I run bonito as:

`/home/bonito/venv3/bin/bonito basecaller dna_r9.4.1 --batch 16 --chunksize 2070 --reference ref.mmi --save-ctc <folder fast5> > bonito_calls.sam`

But the error says "you tried to allocate 589824". I have changed the parameters in basecall.py, but still the same error message. See below.

```
> loading model
Traceback (most recent call last):
  File "/home/bonito/venv3/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito', 'console_scripts', 'bonito')())
  File "/lustre7/home/bonito/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/lustre7/home/bonito/bonito/cli/basecaller.py", line 28, in main
    model = load_model(args.model_directory, args.device, weights=int(args.weights))
  File "/lustre7/home/bonito/bonito/util.py", line 298, in load_model
    model = Model(config)
  File "/lustre7/home/bonito/bonito/crf/model.py", line 186, in __init__
    encoder = rnn_encoder(seqdist.n_base, seqdist.state_len, insize=config['input']['features'], **config['encoder'])
  File "/lustre7/home/bonito/bonito/crf/model.py", line 149, in rnn_encoder
    rnn(features, features, reverse=True), rnn(features, features),
  File "/lustre7/home/bonito/bonito/nn.py", line 194, in __init__
    super().__init__(torch.nn.LSTM, size, insize, bias=bias, reverse=reverse)
  File "/lustre7/home/bonito/bonito/nn.py", line 159, in __init__
    self.init_orthogonal(orthogonal_weight_init)
  File "/lustre7/home/bonito/bonito/nn.py", line 181, in init_orthogonal
    orthogonal_(x[i:i+self.rnn.hidden_size])
  File "/lustre7/home/bonito/venv3/lib/python3.7/site-packages/torch/nn/init.py", line 442, in orthogonal_
    q, r = torch.qr(flattened)
RuntimeError: [enforce fail at CPUAllocator.cpp:67] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 589824 bytes. Error code 12 (Cannot allocate memory)
```

Any suggestion?

**Comment by iiSeymour** [comment]
@gushiro how much memory does your GPU have and is there anything else running on it?

**Comment by gushiro** [comment]
I partially solve the problem by adding more memory in the job submission
