### ISSUE TITLE
Assertion on trying to evaluate a model

### ISSUE THREAD

**Issue by singagan** [nanoporetech/bonito#189]
Hi,
I am getting the below assertion. I tried to replace some of the bonito layers to train a model with different architecture. When I tried to evaluate (using bonito evaluate command), I got the below error. 

Even while using pre-trained models, I am getting this issue. 

I would appreciate any help on this.

Traceback (most recent call last):
  File "bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito-cuda111', 'console_scripts', 'bonito')())
  File "bonito/__init__.py", line 34, in main
    args.func(args)
  File "bonito/cli/evaluate.py", line 43, in main
    model = load_model(args.model_directory, args.device, weights=w)
  File "bonito/util.py", line 302, in load_model
    state_dict = {k2: state_dict[k1] for k1, k2 in match_names(state_dict, model).items()}
  File "bonito/util.py", line 275, in match_names
    assert s1 == s2
**AssertionError**

**Comment by iiSeymour** [comment]
As you have modified the model architecture you won't be able to load the weights of one of the pre-trained models provided by bonito, you need to make sure the model type and weights match.

**Comment by singagan** [comment]
Thanks for the quick reply, @iiSeymour! 
Actually, I get the same error on using weights from my new model. I am trying to debug but not sure what I am missing.

When you say model type, do you mean in the config.toml file?

**Comment by iiSeymour** [comment]
The [`model.package`](https://github.com/nanoporetech/bonito/blob/master/bonito/models/configs/dna_r9.4.1%40v3.toml#L4) in the config sets which PyTorch Model should be created. Look at `bonito.util.load_model`, you need your `Model` *(PyTorch Model object)* and the model weights you are trying to load to match.

**Comment by singagan** [comment]
I think everything is right. I added from prints in `bonito.util.load_model` to check which model is being loaded.
* loading data
* loading model 0
dirname:  models_quant/acinetobacter/new_model
weights:  models_quant/acinetobacter/new_model/weights_1.tar
Model:  <class 'bonito.ctc.model.Model'>

I am following the below steps:
1) I update[model.py](https://github.com/nanoporetech/bonito/blob/master/bonito/ctc/model.py)
2) Then I train using I use [dna_r9.4.1%40v1.toml](https://github.com/nanoporetech/bonito/blob/master/bonito/models/configs/dna_r9.4.1%40v1.toml) on my reads using the below command (I have prepared the training data)
  bonito train --directory data/acinetobacter/training  models_quant/acinetobacter/new_model --config models/configs/dna_r9.4.1\@v1.toml --batch 16 -f --no-amp --epochs 1
3) Then when I try to evaluate I get the above assertion.
 bonito evaluate --directory data/acinetobacter/training --batch 32 models_quant/acinetobacter/new_model

**Comment by singagan** [comment]
I think the issue is because of the new activation that I added. 
To add a new activation I made the following two changes: 1) added the activation function in [nn.py](https://github.com/nanoporetech/bonito/blob/35aa83ce73891fc8c51a44a2abac14a27f897a1d/bonito/nn.py#L19).
2) updated activation in [config.toml](https://github.com/nanoporetech/bonito/blob/35aa83ce73891fc8c51a44a2abac14a27f897a1d/bonito/models/configs/dna_r9.4.1%40v1.toml#L13) file with the name of that new activation function.

Do I need to update in some other place as well so that I have consistency everywhere?

Thanks in advance!

**Comment by singagan** [comment]
**Update:** I see that after using a different activation function, there are some features in the weights that are not part of the model dict. This mismatch leads to the assertion. How could I update the model dict for these missing attributes?

**Comment by iiSeymour** [comment]
Activations don't have parameters and shouldn't be the issue here - the best thing to do is step through the model loading code to check what the layer differences are.

**Comment by singagan** [comment]
Thanks, I am going through the code right now.
Attached is a screenshot where I have selected some of the missing attributes. I see these being added after I change the activation, which are missing in the model.
![image](https://user-images.githubusercontent.com/53442471/135822490-77f9d327-0bc3-4f71-b6d6-e970b44062c0.png)

**Comment by iiSeymour** [comment]
Ah okay, because of the quantization the scaling factors for the model activation are stored. You are going to need to update the model loading to account for your quantization changes.

**Comment by singagan** [comment]
Ah I see. What would be the best way to handle it? I see that the [encoder_layers list](https://github.com/nanoporetech/bonito/blob/35aa83ce73891fc8c51a44a2abac14a27f897a1d/bonito/ctc/model.py#L74) contains those scaling factor keys, but I am not sure where should I add these missing keys to the model dict so that when we call [state_dict.items() ](https://github.com/nanoporetech/bonito/blob/35aa83ce73891fc8c51a44a2abac14a27f897a1d/bonito/util.py#L274), I get the right keys.

Right now, I am doing a hacky way by commenting the dict check at [lin 301](https://github.com/nanoporetech/bonito/blob/35aa83ce73891fc8c51a44a2abac14a27f897a1d/bonito/util.py#L301). 
The basecalling seems to work and provides some accuracy results. Not sure if it is the right way though?
