### ISSUE TITLE
Basecalling issues relating to CUDA and cupy

### ISSUE THREAD

**Issue by mbhall88** [nanoporetech/bonito#196]
Hi,

I have been struggling for a few days with bonito and I can't seem to get it to work.

I'll provide a thorough description of versions and install instructions and pray that someone has a solution.

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
$ python -V
Python 3.8.8
$ nvidia-smi
Thu Nov 11 23:35:01 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:B1:00.0 Off |                    0 |
| N/A   40C    P0    26W / 250W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I am working on an LSF cluster system and all commands are run on an interactive job on the above GPU, with exclusive mode on (i.e., no one else is sharing the GPU).

My CUDA install is a module on our cluster so I set the following environment variables for cupy as per [their instructions](https://docs.cupy.dev/en/stable/install.html#working-with-custom-cuda-installation).

```
$ export CUDA_PATH=/hps/software/spack/opt/spack/linux-centos8-sandybridge/gcc-9.3.0/cuda-11.1.1-oqr2b7d6y2frk6iuvsrc66vepqrvhz5d
$ export LD_LIBRARY_PATH="${CUDA_PATH}/lib64:$LD_LIBRARY_PATH"
$ export PATH="${CUDA_PATH}/bin:$PATH"
```

I have tried the following in a conda enviroment and in a virtualenv and get the exact same issues either way. The following is done inside the cloned bonito repository (commit https://github.com/nanoporetech/bonito/commit/62050ba32fac20b1e82f1349aaaaf41512a7008c).

```
# change USE_CUDA111 = True in setup.py
$ python -m venv .venv
$ source .venv/bin/activate
$ python -m pip install -U pip setuptools
# I use no cache dir here to ensure I am always trying a clean install
$ python -m pip install -f https://download.pytorch.org/whl/torch_stable.html --no-cache-dir -r requirements-cuda111.txt
$ python -m pip install -e .
$ bonito download --models --latest -f
```

Everything works without error to this point.

I have a single multi-fast5 file to test out basecalling. My ultimate aim for using bonito is to train a model though.

```
$ bonito basecaller --reference ../data/assemblies/BCG.mmi --fastq --save-ctc dna_r9.4.1 fast5/ > ctc-dir/basecalls.sam
> loading model
> loading reference
> calling: 0 reads [00:00, ? reads/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/nfs/research/zi/mbhall/Software/.pyenv/versions/3.8.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/hps/nobackup/iqbal/mbhall/tubby/bonito/bonito/multiprocessing.py", line 194, in run
    for i, (k, v) in enumerate(self.iterator):
  File "/hps/nobackup/iqbal/mbhall/tubby/bonito/bonito/crf/basecall.py", line 112, in <genexpr>
    stitched = (
  File "/hps/nobackup/iqbal/mbhall/tubby/bonito/bonito/util.py", line 221, in <genexpr>
    return (
  File "/hps/nobackup/iqbal/mbhall/tubby/bonito/bonito/util.py", line 216, in <genexpr>
    batches = (
  File "/hps/nobackup/iqbal/mbhall/tubby/bonito/bonito/crf/basecall.py", line 109, in <genexpr>
    (k, quantise_int8(compute_scores(model, batch, reverse=reverse)))
  File "/hps/nobackup/iqbal/mbhall/tubby/bonito/bonito/crf/basecall.py", line 41, in compute_scores
    betas = model.seqdist.backward_scores(scores.to(torch.float32))
  File "/hps/nobackup/iqbal/mbhall/tubby/bonito/bonito/crf/model.py", line 61, in backward_scores
    return seqdist.sparse.bwd_scores_cupy(Ms, self.idx, beta_T, S, K=1)
  File "/hps/nobackup/iqbal/mbhall/tubby/bonito/.venv/lib/python3.8/site-packages/seqdist/sparse.py", line 145, in bwd_scores_cupy
    cupy_func('bwd_scores', Ms.dtype, S, NZ, K)(grid=(N, 1, 1), block=(C//K, 1, 1), shared_mem=2*_bytes*C,
  File "/hps/nobackup/iqbal/mbhall/tubby/bonito/.venv/lib/python3.8/site-packages/seqdist/utils.py", line 61, in wrapped
    return raw_kernel(grid, block, args, shared_mem=shared_mem)
  File "cupy/core/raw.pyx", line 82, in cupy.core.raw.RawKernel.__call__
  File "cupy/core/raw.pyx", line 89, in cupy.core.raw.RawKernel.kernel.__get__
  File "cupy/core/raw.pyx", line 106, in cupy.core.raw.RawKernel._kernel
  File "cupy/_util.pyx", line 59, in cupy._util.memoize.decorator.ret
  File "cupy/core/raw.pyx", line 525, in cupy.core.raw._get_raw_module
  File "cupy/core/core.pyx", line 1838, in cupy.core.core.compile_with_cache
  File "cupy/core/core.pyx", line 1894, in cupy.core.core.compile_with_cache
  File "/hps/nobackup/iqbal/mbhall/tubby/bonito/.venv/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 370, in compile_with_cache
    return _compile_with_cache_cuda(
  File "/hps/nobackup/iqbal/mbhall/tubby/bonito/.venv/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 479, in _compile_with_cache_cuda
    mod.load(cubin)
  File "cupy/cuda/function.pyx", line 241, in cupy.cuda.function.Module.load
  File "cupy/cuda/function.pyx", line 243, in cupy.cuda.function.Module.load
  File "cupy_backends/cuda/api/driver.pyx", line 246, in cupy_backends.cuda.api.driver.moduleLoadData
  File "cupy_backends/cuda/api/driver.pyx", line 124, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_INVALID_PTX: a PTX JIT compilation failed
```

The odd thing is, after receiving this error, the command does not actually exit - i.e., it's like the shell still says the bonito command is running. I have to kill the shell session as <kbd>Ctrl+c</kbd> does nothing.

**Comment by kapsakcj** [comment]
taking a wild guess here, I could be totally wrong...It might be that your CUDA versions don't exactly match. `nvidia-smi` shows CUDA 11.0 and your CUDA_PATH shows `[...]/cuda-11.1.1[...]` which might be enough of a version difference to cause issues.

Any way you could match versions more precisely and use 11.0?

The bit at the end of the error message makes me think it has to do with the drivers installed and the accompanying CUDA version.

`cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_INVALID_PTX: a PTX JIT compilation failed`

**Comment by mbhall88** [comment]
Hmm interesting. Sadly there isn't too much I can do about the CUDA versions on our cluster. Weird that I don't have any problems with any other programs that use GPUs.

**Comment by mbhall88** [comment]
An update. I have asked my systems team if they can upgrade the nvidia driver versions.

Looking at https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html it seems that in order to run CUDA 11.1 (or above), you need NVIDIA drivers >=450.80.02 (ours is 450.51.06). There is a note in that document that also says that updating to >=450.80.02 will maintain compatibility with CUDA 11.0 - so this update *might* be the solution.

I'll check back in when/if the drivers are updated.

**Comment by iiSeymour** [comment]
Hey @mbhall88 

Really sorry to hear about the issues you have been having. I actually think this is an issue with CuPy 8.4.0 and newer drivers, I suspect if you update the requirements files to use the latest version of CuPy _(9.6.0)_ then the issue should be resolved.

Let me know if it does and we can't get it sorted on master.

HTH

Chris.

**Comment by mbhall88** [comment]
🎉 That worked @iiSeymour 🎉 

I changed the cupy line in the cuda 11.1 requirements file to `cupy-cuda111==9.6.*` (currently this used v9.6.0)

I was able to basecall and I *think* I was able to train.

The reason I say *think* was that there was a bunch of error messages dumped to stderr like this 

```
Traceback (most recent call last):
  File "/hps/software/users/iqbal/mbhall/miniconda3/envs/bonito/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/hps/software/users/iqbal/mbhall/miniconda3/envs/bonito/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/hps/software/users/iqbal/mbhall/miniconda3/envs/bonito/lib/python3.8/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/hps/software/users/iqbal/mbhall/miniconda3/envs/bonito/lib/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/hps/software/users/iqbal/mbhall/miniconda3/envs/bonito/lib/python3.8/shutil.py", line 675, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/hps/software/users/iqbal/mbhall/miniconda3/envs/bonito/lib/python3.8/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs27411643fb83351600003e96'
Traceback (most recent call last):
  File "/hps/software/users/iqbal/mbhall/miniconda3/envs/bonito/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/hps/software/users/iqbal/mbhall/miniconda3/envs/bonito/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/hps/software/users/iqbal/mbhall/miniconda3/envs/bonito/lib/python3.8/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/hps/software/users/iqbal/mbhall/miniconda3/envs/bonito/lib/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/hps/software/users/iqbal/mbhall/miniconda3/envs/bonito/lib/python3.8/shutil.py", line 675, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/hps/software/users/iqbal/mbhall/miniconda3/envs/bonito/lib/python3.8/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs7d7d80f76300f12100003e97'
[epoch 5] directory=model-dir loss=0.3725 mean_acc=85.103% median_acc=85.526%
```

However, the process exited with code 0 and the model directory has the following contents

```
Permissions Size User     Group Date Modified Name
.rw-rw-r--   664 mbhall88 iqbal 15 Nov 05:13  config.toml
.rw-rw-r--  3.7k mbhall88 iqbal 15 Nov 05:16  losses_1.csv
.rw-rw-r--  3.7k mbhall88 iqbal 15 Nov 05:16  losses_2.csv
.rw-rw-r--  3.6k mbhall88 iqbal 15 Nov 05:17  losses_3.csv
.rw-rw-r--  3.6k mbhall88 iqbal 15 Nov 05:17  losses_4.csv
.rw-rw-r--  3.7k mbhall88 iqbal 15 Nov 05:18  losses_5.csv
.rw-rw-r--   575 mbhall88 iqbal 15 Nov 05:18  training.csv
.rw-rw-r--  108M mbhall88 iqbal 15 Nov 05:16  weights_1.tar
.rw-rw-r--  108M mbhall88 iqbal 15 Nov 05:16  weights_2.tar
.rw-rw-r--  108M mbhall88 iqbal 15 Nov 05:17  weights_3.tar
.rw-rw-r--  108M mbhall88 iqbal 15 Nov 05:17  weights_4.tar
.rw-rw-r--  108M mbhall88 iqbal 15 Nov 05:18  weights_5.tar
```

I'm not sure what the expected output is though so I'll dump the config here and maybe you could comment on whether it looks finished (I only trained/basecalled 2 multifast5 files)?

```
[model]
package = "bonito.crf"

[labels]
labels = [ "N", "A", "C", "G", "T",]

[input]
features = 1

[qscore]
bias = 0.0
scale = 1.0

[encoder]
stride = 5
winlen = 19
scale = 5.0
features = 768
rnn_type = "lstm"
activation = "swish"
blank_score = 2.0

[global_norm]
state_len = 5

[training]
command = "train"
training_directory = "model-dir"
config = "/hps/nobackup/iqbal/mbhall/tubby/bonito/bonito/models/configs/dna_r9.4.1@v3.1.toml"
pretrained = ""
directory = "PosixPath('ctc-dir')"
device = "cuda"
lr = 0.002
seed = 25
epochs = 5
batch = 64
chunks = 0
valid_chunks = 0
no_amp = false
multi_gpu = false
force = true
func = "<function main at 0x1549091853a0>"
```

I am using a GPU node on a computing cluster that is shared by others and I didn't request an exlusive process so maybe those errors are just related to that?

**Comment by iiSeymour** [comment]
Good to hear @mbhall88 I've updated master to use the latest PyTorch and CuPy.

The `OSError` you are seeing is when the Python multiprocessing module is trying to remove some temporary files it has created, not a bonito problem but an issue with your NFS by the looks of it.

**Comment by mbhall88** [comment]
> The OSError you are seeing is when the Python multiprocessing module is trying to remove some temporary files it has created, not a bonito problem but an issue with your NFS by the looks of it.

Makes sense. It doesn't stop the training from running so I'll just ignore it.

I can confirm the top of master (02fb9f8) works perfectly fine for me.
