### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by elohimarthur** [nanoporetech/bonito#205]
Dear researcher,
When I use bonito to basecaller my reads, cuda out of memory. How to fix it? Thank you for replying!
Here is my error:

```
Traceback (most recent call last):
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/site-packages/bonito/multiprocessing.py", line 110, in run
    for item in self.iterator:
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/site-packages/bonito/crf/basecall.py", line 69, in <genexpr>
    (read, compute_scores(model, batch, reverse=reverse)) for read, batch in batches
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/site-packages/bonito/crf/basecall.py", line 32, in compute_scores
    scores = model(batch.to(dtype).to(device))
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/site-packages/bonito/crf/model.py", line 168, in forward
    return self.encoder(x)
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/site-packages/bonito/nn.py", line 104, in forward
    scores = self.activation(scores)
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 349, in forward
    return torch.tanh(input)
RuntimeError: CUDA out of memory. Tried to allocate 2.93 GiB (GPU 0; 8.00 GiB total capacity; 4.01 GiB already allocated; 2.32 GiB free; 4.04 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by iiSeymour** [comment]
Each models default configuration will use around 11GB of GPU memory but you can reduce the `batchsize` to use less.

Add `-v` to `bonito basecaller` to see what the default `batchsize` is for a given model.

```
$ bonito basecaller -v dna_r9.4.1_e8_sup@v3.3 ...                             
> loading model dna_r9.4.1_e8_sup@v3.3
> model basecaller params: {'batchsize': 128, 'chunksize': 10000, 'overlap': 500, 'quantize': None}
```

Reducing the `batchsize` for the `sup` models from 128 to 64 will reduced the memory requirement to ~6.5GB.

```
$ bonito basecaller --batchsize 64 dna_r9.4.1_e8_sup@v3.3 ...
```

_Note: the default batchsize for accrosss `{fast,hac,sup}` is different._

**Comment by elohimarthur** [comment]
> 

Thank you for your replying! And I try to reduce the batchsize. It goes error:


$ bonito basecaller -v  --batchsize 64 ./anaconda3/envs/nano3/lib/python3.8/site-packages/bonito/models/dna_r9.4.1_e8_sup@v3.3 ./data2
> loading model ./anaconda3/envs/nano3/lib/python3.8/site-packages/bonito/models/dna_r9.4.1_e8_sup@v3.3
> model basecaller params: {'batchsize': 64, 'chunksize': 10000, 'overlap': 500, 'quantize': None}
> outputting unaligned fastq
> calling: 0 reads [00:00, ? reads/s]Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/site-packages/bonito/multiprocessing.py", line 110, in run
    for item in self.iterator:
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/site-packages/bonito/crf/basecall.py", line 69, in <genexpr>
    (read, compute_scores(model, batch, reverse=reverse)) for read, batch in batches
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/site-packages/bonito/crf/basecall.py", line 35, in compute_scores
    sequence, qstring, moves = beam_search(
  File "/home/eloher/anaconda3/envs/nano3/lib/python3.8/site-packages/koi/decode.py", line 13, in beam_search
    raise TypeError('Expected fp16 but received %s' % scores.dtype)
TypeError: Expected fp16 but received torch.float32

**Comment by mulderdt** [comment]
I am having the same issues. I reduced batchsize to 64 with hac and got the same error as above.
I am using python 3.8 and CUDA 10.2

`(venv3.8) david@david-desktop:~/tools/bonito$ bonito basecaller -v --batchsize 64 dna_r10.4_e8.1_hac@v3.4 /media/david/WD_BLACK/20220128_ONT_WGS_Experiment_16/CG06604_DNA-37676_Library_16A/20220128_1513_MN33949_FAR83679_7d57d8fc/fast5-sub --modified-bases 5mC --reference /media/david/data/genomes/ucsc.hg19.fa > /media/david/data/pipeline/20220128_ONT_WGS_Experiment_16/hac-10.4-e8.1-3.4-basecalls_with_mods.bam
> loading model dna_r10.4_e8.1_hac@v3.4
> model basecaller params: {'batchsize': 64, 'chunksize': 12000, 'overlap': 600, 'quantize': None}
> loading modified base model
> warning (remora): Remora model for basecall model version (v3.4) not found. Using default Remora model for dna_r10.4_e8.1_hac.
> loaded modified base model to call (alt to C): m=5mC
> loading reference
> outputting aligned bam
> calling: 0 reads [00:00, ? reads/s]Exception in thread Thread-7:                                  
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/david/tools/bonito/bonito/multiprocessing.py", line 110, in run
    for item in self.iterator:
  File "/home/david/tools/bonito/bonito/crf/basecall.py", line 69, in <genexpr>
    (read, compute_scores(model, batch, reverse=reverse)) for read, batch in batches
  File "/home/david/tools/bonito/bonito/crf/basecall.py", line 35, in compute_scores
    sequence, qstring, moves = beam_search(
  File "/home/david/tools/bonito/venv3.8/lib/python3.8/site-packages/koi/decode.py", line 13, in beam_search
    raise TypeError('Expected fp16 but received %s' % scores.dtype)
TypeError: Expected fp16 but received torch.float32`

**Comment by sabiqali** [comment]
Hi,

I am not sure if this is an exact solution, I was getting this exact error when running modified basecalling. 

I then used this issue: #140 and set `export OMP_NUM_THREADS=1`.

This seemed to work and I don't get the CUDA out of memory error anymore. I don't know if this would be a permanent fix but it seemed to solve the issue for now and I can proceed with my analysis.

**Comment by davidnewman02** [comment]
Closing due to inactivity.
Please try again with the latest version of Bonito and feel free to open a new ticket if you have further issues.
