### ISSUE TITLE
basecaller save-ctc TypeError

### ISSUE THREAD

**Issue by thackl** [nanoporetech/bonito#207]
I'm trying to train a model on my own R10.3 data. But I get an exception when basecalling with the `--save-ctc` flag. The same basecaller command w/o `--save-ctc` works.

```
premodel="dna_r10.4_e8.1_sup@v3.4"
bonito basecaller $premodel --save-ctc --reference lambda.mmi lambda/20210412_1612_MN35152_FAP05092_20b8ec41/fast5_pass > training/ctc-data/basecalls.sam
> loading model dna_r10.4_e8.1_sup@v3.4
> loading reference
> outputting aligned sam
> preprocessing reads ...
Traceback (most recent call last):                                                                  
  File "/nfs/bmm/crov/CroV-complex/nanopore/bonito-env/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/nfs/bmm/crov/CroV-complex/nanopore/bonito-env/lib64/python3.6/site-packages/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/nfs/bmm/crov/CroV-complex/nanopore/bonito-env/lib64/python3.6/site-packages/bonito/cli/basecaller.py", line 133, in main
    ref_fn=args.reference, groups=groups,
TypeError:or: __init__() got an unexpected keyword argument 'group_key'
```

**Comment by iiSeymour** [comment]
Fixed in https://github.com/nanoporetech/bonito/commit/6abe9f054e2ab667cf35453af50ef30d05958984
