### ISSUE TITLE
basecaller compute_scores koi TypeError

### ISSUE THREAD

**Issue by jdemeul** [nanoporetech/bonito#208]
Hi @iiSeymour and thanks a lot for this great basecaller.

With the new Bonito v0.5.0 (e4a8e11), I seem to get the following error with a cuda113 install on an nvidia/cuda docker and a P100 SXM2:

```
bonito basecaller \
    dna_r9.4.1_e8_sup@v3.3 \
    ./fast5_subset/ \
    > basecalls.fasta
> loading model dna_r9.4.1_e8_sup@v3.3
> outputting unaligned fastq
> calling: 0 reads [00:00, ? reads/s]Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/bonito/bonito/multiprocessing.py", line 110, in run
    for item in self.iterator:
  File "/bonito/bonito/crf/basecall.py", line 69, in <genexpr>
    (read, compute_scores(model, batch, reverse=reverse)) for read, batch in batches
  File "/bonito/bonito/crf/basecall.py", line 35, in compute_scores
    sequence, qstring, moves = beam_search(
  File "/bonito/venv3/lib/python3.8/site-packages/koi/decode.py", line 13, in beam_search
    raise TypeError('Expected fp16 but received %s' % scores.dtype)
TypeError: Expected fp16 but received torch.float32
```

I also tried the cuda102 version on the corresponding nvidia docker, which hangs at the same step `calling: 0 reads [00:00, ? reads/s]` with the same error. 
Happy to provide any further info.

**Comment by jdemeul** [comment]
It seems like Bonito is enforcing a threshold CUDA capability >= 7 to assess FP16 support, while the P100 is at 6 (and supports FP16).
Lowering the threshold in `bonito.util.half_supported()` from 7 to 6 as indicated below seems to resolve my issues.

```
def half_supported():
    """
    Returns whether FP16 is support on the GPU
    """
    try:
        return get_device_capability()[0] >= 6
    except:
        return False
```

**Comment by jdemeul** [comment]
One more update – I've just had a go and can confirm the original container runs smoothly on an system with an RTX3090 (Ubuntu 20.04)

**Comment by amijalis** [comment]
Did you ever figure this out? I'm having the same issue when trying to run Bonito in a container with a K80 GPU.

**Comment by jdemeul** [comment]
Afraid not, I'm currently stuck running Bonito 0.5.0 on that RTX3090 workstation and 0.3.8 (have not tried 0.4) on our P100 cluster.

**Comment by davidnewman02** [comment]
Closing due to inactivity.
Please try again with the latest version of Bonito/Koi and feel free to open a new ticket if you have further issues.
