### ISSUE TITLE
Problems installing and with the first run

### ISSUE THREAD

**Issue by fernanarr** [nanoporetech/bonito#250]
Hi,

I've been trying to install bonito, but I'm getting some errors.
First, I've used the instructions to install using pip as showed in the main bonito page.

Bonito seems to be installed correctly but, when I try to run the first execution, I get this error:

`bonito basecaller dna_r9.4.1_e8_fast@v3.4 /data/reads > basecalls.bam
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in function __import__> returned a result with an error set
Traceback (most recent call last):
  File "/home/fernando/.local/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/home/fernando/.local/lib/python3.8/site-packages/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/fernando/.local/lib/python3.8/site-packages/bonito/cli/basecaller.py", line 26, in main
    init(args.seed, args.device)
  File "/home/fernando/.local/lib/python3.8/site-packages/bonito/util.py", line 53, in init
    assert(torch.cuda.is_available())
AssertionError`

To solve this error, I've updated numpy using pip install numpy --upgrade, and I get some errors during the installation:
` pip install numpy --upgrade
Collecting numpy
  Using cached numpy-1.22.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
ERROR: ont-bonito 0.5.1 has requirement numpy~=1.19.5, but you'll have numpy 1.22.3 which is incompatible.
ERROR: ont-bonito-cuda113 0.5.1 has requirement numpy~=1.19.5, but you'll have numpy 1.22.3 which is incompatible.
ERROR: ont-bonito-cuda113 0.5.1 has requirement torch==1.10.0+cu113, but you'll have torch 1.10.1 which is incompatible.
ERROR: ont-bonito-cuda111 0.5.1 has requirement numpy~=1.19.5, but you'll have numpy 1.22.3 which is incompatible.
ERROR: ont-bonito-cuda111 0.5.1 has requirement torch==1.10.0+cu111, but you'll have torch 1.10.1 which is incompatible.
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
Successfully installed numpy-1.22.3`

But, when I try to run the first execution of bonito, I get this assertion error:

` bonito basecaller dna_r9.4.1_e8_fast@v3.4 /data/reads > basecalls.bam
Traceback (most recent call last):
  File "/home/fernando/.local/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/home/fernando/.local/lib/python3.8/site-packages/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/fernando/.local/lib/python3.8/site-packages/bonito/cli/basecaller.py", line 26, in main
    init(args.seed, args.device)
  File "/home/fernando/.local/lib/python3.8/site-packages/bonito/util.py", line 53, in init
    assert(torch.cuda.is_available())
AssertionError`

The path to fast5 files is correct, but the output is an empty basecalls.bam file

I've also tried to fully uninstall numpy, and then install the 1.19.5 version, but it's not working either.

Could you please help me to figure out what might be happening?

Thanks in advance

**Comment by iiSeymour** [comment]
Hey @fernanarr does your device have an Nvidia GPU in it?

**Comment by fernanarr** [comment]
Hi @iiSeymour, thanks for your reply. 
We have an Nvidia basic GPU with only 2GB, but this week we will install in our device an RTX3070TI model. Then I'll try again to run it.

**Comment by fernanarr** [comment]
Hello again @iiSeymour Now, with the new RTX 3070 TI, Bonito is working after solving a few problems with pytorch and CUDA versions.

We've tried to make a first run with this command:
`bonito basecaller dna_r9.4.1_e8.1_fast@v3.4 /data/reads > basecalls.fastq`
with a single fast5 file in the reads directory

The program works but our .bam output file is empty.

`> loading model dna_r9.4.1_e8.1_fast@v3.4
> outputting unaligned fastq
> completed reads: 0
> duration: 0:00:00
> samples per second 0.0E+00
> done`

GPU seems to be working correctly.

Is there anything else that we need to set up for the first run?

Thanks in advance.

Regards

**Comment by iiSeymour** [comment]
@fernanarr are you sure you have at least one  `*.fast5` file in `/data/reads` - bonito is reporting 0 reads found? If your fast5 file is not directly in the folder you specified you'll need to add `--recursive` to search the whole directory tree. Also note, you have set the output to `.fastq`, not `.bam`.

**Comment by fernanarr** [comment]
@iiSeymour thanks a lot for yor quick reply.

My bad with the` .fastq `output, I've copied the wrong command in my post. I'm using `.bam`
I've checked that there is a `.fast5` file in the reads directory, and I've tried also to use `/data -- recursive`  as you suggested to check if it can be a solution.
`bonito basecaller dna_r9.4.1_e8.1_fast@v3.4 bonito/data --recursive > `basecalls.bam` `

I'm getting the same result and I don't know what might be happenning

Thanks for your help

**Comment by DjampaKozlowski** [comment]
Hello @fernanarr, 

I'm new to bonito so I'm not sur it will help but could it be a matter of argument position (the --recursive argument position to be clear) ? From what I understand, the tools options must be between the model and the input data. 

Hence, the command should be  `bonito basecaller dna_r9.4.1_e8.1_fast@v3.4 --recursive  bonito/data    >    basecalls.bam`

In my case, I try to fine tune a model and the following command worked : 
`bonito basecaller dna_r9.4.1_e8.1_sup@v3.3 --save-ctc --recursive --device cuda:0 --reference <ref. genome> <fast5 data parent dir> > <ouput>`

Best regards

**Comment by fernanarr** [comment]
Hi @DjampaKozlowski 

Thanks for your help, but same result after changing the argument position.

Seems that bonito is not identifying the fast5 file in the data folder and the result is still an empty file

`> loading model dna_r9.4.1_e8.1_fast@v3.4
> outputting unaligned bam
> completed reads: 0
> duration: 0:00:00
> samples per second 0.0E+00
> done`

**Comment by DjampaKozlowski** [comment]
Hello @fernanarr, 

I'm glad it worked ! And thank you for your tip because I just encountered the same issue ! What a timing ! ^^

Best regards,
Djampa

**Comment by fernanarr** [comment]
Great!

With an Nvidia GTX 3070TI I've tried a batchsize of 1390 without any trouble. Just in case it helps you.

**Comment by ThayMorais** [comment]
Hey,
I'm trying to use remora/bonito to do my methylation analysis and I faced the same errors reported here and I also tried to fix it with what you guys described but I'm still getting the same errors... I'm new in the bioinformatics world... so could I have any help in resolving it?

Kind regards,

Thayara

**Comment by sklages** [comment]
@ThayMorais

You should probably provide a bit more info on what you have been doing:
- what kind of data?
- what kind of GPU? Memory?
- OS? Nvidia driver/CUDA version?
- which software versions?
- how did you run the program and what error did you get?

**Comment by martinjvickers** [comment]
I'm also having these same issues, 

```
$ nvidia-smi
Thu May 18 13:40:03 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100 80G...  On   | 00000000:17:00.0 Off |                    0 |
| N/A   34C    P0    55W / 300W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |

```

```
bonito -v
bonito 0.7.0
```

Bonito installed using singularity in a Ubuntu focal container and I get the same error that starts all this;

```$ singularity exec ~/bin/bonito.img bonito basecaller dna_r9.4.1_e8_fast@v3.4 --device cuda:0 test
Traceback (most recent call last):
  File "/usr/local/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/bonito/cli/basecaller.py", line 26, in main
    init(args.seed, args.device)
  File "/usr/local/lib/python3.8/dist-packages/bonito/util.py", line 53, in init
    assert(torch.cuda.is_available())
AssertionError
```

In an earlier comment;

> Hello again @iiSeymour Now, with the new RTX 3070 TI, Bonito is working after solving a few problems with pytorch and CUDA versions.

what were the issues that were solved? I'm not seeing anything wrong with my install.

**Comment by davidnewman02** [comment]
Closing as resolved.
If you have further compatibility errors on the latest version of bonito please raise a new ticket.
