### ISSUE TITLE
NameError: name 'default_data' is not defined

### ISSUE THREAD

**Issue by shy0625** [nanoporetech/bonito#255]
Hi, I followed the steps:
"
bonito dowdload training
bonito train /data/training/model-dir
"
then I got this error:

"
[loading data]
Traceback (most recent call last):
  File "/mnt/software-install/miniconda3/envs/theano/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito', 'console_scripts', 'bonito')())
  File "/home/sunhuiyuan/bonito/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/sunhuiyuan/bonito/bonito/cli/train.py", line 37, in main
    train_loader_kwargs, valid_loader_kwargs = load_numpy(
  File "/home/sunhuiyuan/bonito/bonito/data.py", line 40, in load_numpy
    train_data = load_numpy_datasets(limit=limit, directory=directory)
  File "/home/sunhuiyuan/bonito/bonito/data.py", line 61, in load_numpy_datasets
    directory = default_data
NameError: name 'default_data' is not defined
"

Actually, I can't find the training file under data file.

Could you please help me figure out it why ? 

What does 'model-dir' refer ?

thanks.

**Comment by shy0625** [comment]
![d00c38b8a31fd419412b39592562a11](https://user-images.githubusercontent.com/35022594/170452831-00fad047-a660-49f6-a24d-41872c368b90.png)
