### ISSUE TITLE
Error with protocol buffers

### ISSUE THREAD

**Issue by jdemeul** [nanoporetech/bonito#260]
Hi,

I've been installing Bonito using pip in Docker containers for a while now.
Rebuilding with v0.5.3 I'm getting the following error however:

```
(base) ➜  v0.5.3 git:(master) ✗ docker run -it zeunas/bonito:0.5.3 bash
root@19f018637b3a:/# bonito --help
Traceback (most recent call last):
  File "/usr/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito==0.5.3', 'console_scripts', 'bonito')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/bonito/__init__.py", line 2, in <module>
    from bonito.cli import basecaller, train, evaluate, view, convert, download, export
  File "/usr/lib/python3.8/site-packages/bonito/cli/basecaller.py", line 18, in <module>
    from bonito.mod_util import call_mods, load_mods_model
  File "/usr/lib/python3.8/site-packages/bonito/mod_util.py", line 6, in <module>
    from remora.model_util import load_model
  File "/usr/lib/python3.8/site-packages/remora/model_util.py", line 11, in <module>
    import onnx
  File "/usr/lib/python3.8/site-packages/onnx/__init__.py", line 11, in <module>
    from onnx.external_data_helper import load_external_data_for_model, write_external_data_tensors, convert_model_to_external_data
  File "/usr/lib/python3.8/site-packages/onnx/external_data_helper.py", line 14, in <module>
    from .onnx_pb import TensorProto, ModelProto
  File "/usr/lib/python3.8/site-packages/onnx/onnx_pb.py", line 8, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "/usr/lib/python3.8/site-packages/onnx/onnx_ml_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

This is fixed by explicitly installing bonito with `pip install ont-bonito protobuf==3.20.1`.
You may wish to add this to the requirements or regenerate as indicated?

Thanks again for the great work!

**Comment by JacobHayes** [comment]
FYI: I think this is an issue upstream with ONNX (hence nothing for bonito to regenerate) with the fix [merged today](https://github.com/onnx/onnx/pull/4223). It should be in the next release, but I'm not sure the timeline.

**Comment by jdemeul** [comment]
Good catch, looks like that's the one indeed, thanks!
