### ISSUE TITLE
undefined symbol: host_run_lstm_fwd96

### ISSUE THREAD

**Issue by hasindu2008** [nanoporetech/bonito#263]
I am trying to get this Romora working for a dataset. Installed Bonito latest as per the instructions. I am getting the following error.

```
(bonito-0.5.3) hasindu@genometech-gpgpu:~/scratch/short_read/PQXV22225$ pip install ont-bonito
Collecting ont-bonito
  Downloading ont-bonito-0.5.3.tar.gz (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.8/50.8 kB 12.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting mappy==2.24
  Using cached mappy-2.24.tar.gz (140 kB)
  Preparing metadata (setup.py) ... done
Collecting toml==0.10.2
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting tqdm<5,>4
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting scipy==1.7.3
  Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.1/38.1 MB 35.9 MB/s eta 0:00:00
Collecting numpy~=1.21.5
  Using cached numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Collecting pysam==0.18.0
  Downloading pysam-0.18.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (14.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB 69.1 MB/s eta 0:00:00
Collecting parasail==1.2
  Using cached parasail-1.2-py2.py3-none-manylinux2010_x86_64.whl (14.1 MB)
Collecting pandas<2,>1
  Downloading pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 85.6 MB/s eta 0:00:00
Collecting requests==2.25.1
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting ont-koi==0.0.9
  Downloading ont_koi-0.0.9-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (363 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 kB 63.1 MB/s eta 0:00:00
Collecting onnxruntime==1.11.0
  Downloading onnxruntime-1.11.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 97.2 MB/s eta 0:00:00
Collecting ont-remora==1.1.0
  Downloading ont-remora-1.1.0.tar.gz (42.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 33.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ont-fast5-api==3.3.0
  Using cached ont_fast5_api-3.3.0-py3-none-any.whl (2.0 MB)
Collecting pod5-format==0.0.14
  Downloading pod5_format-0.0.14-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 94.2 MB/s eta 0:00:00
Collecting pod5-format-tools==0.0.14
  Downloading pod5_format_tools-0.0.14-py3-none-any.whl (8.3 kB)
Collecting fast-ctc-decode==0.3.2
  Downloading fast_ctc_decode-0.3.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (517 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 518.0/518.0 kB 73.7 MB/s eta 0:00:00
Collecting python-dateutil==2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting torch~=1.11
  Downloading torch-1.11.0-cp37-cp37m-manylinux1_x86_64.whl (750.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 750.6/750.6 MB 2.3 MB/s eta 0:00:00
Collecting protobuf
  Downloading protobuf-4.21.1-cp37-abi3-manylinux2014_x86_64.whl (407 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 407.8/407.8 kB 57.5 MB/s eta 0:00:00
Collecting flatbuffers
  Using cached flatbuffers-2.0-py2.py3-none-any.whl (26 kB)
Collecting h5py>=2.8
  Downloading h5py-3.7.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (4.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 82.3 MB/s eta 0:00:00
Collecting progressbar33>=2.3.1
  Using cached progressbar33-2.4.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting cffi
  Downloading cffi-1.15.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (427 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 427.1/427.1 kB 65.8 MB/s eta 0:00:00
Collecting onnx
  Downloading onnx-1.11.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 72.7 MB/s eta 0:00:00
Collecting thop
  Using cached thop-0.0.31.post2005241907-py3-none-any.whl (8.7 kB)
Collecting tabulate
  Using cached tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.8/24.8 MB 51.9 MB/s eta 0:00:00
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Collecting iso8601
  Using cached iso8601-1.0.2-py3-none-any.whl (9.7 kB)
Collecting pyarrow~=7.0.0
  Using cached pyarrow-7.0.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
Collecting more-itertools
  Using cached more_itertools-8.13.0-py3-none-any.whl (51 kB)
Collecting pytz
  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2022.5.18.1-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.2/155.2 kB 42.4 MB/s eta 0:00:00
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 24.8 MB/s eta 0:00:00
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting joblib>=0.11
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Using legacy 'setup.py install' for ont-bonito, since package 'wheel' is not installed.
Using legacy 'setup.py install' for mappy, since package 'wheel' is not installed.
Using legacy 'setup.py install' for progressbar33, since package 'wheel' is not installed.
Building wheels for collected packages: ont-remora
  Building wheel for ont-remora (pyproject.toml) ... done
  Created wheel for ont-remora: filename=ont_remora-1.1.0-cp37-cp37m-linux_x86_64.whl size=43469001 sha256=35590ab17a790895894241566f5483e6ed8631d66c1ccbe0853894ca508b3cfb
  Stored in directory: /home/hasindu/.cache/pip/wheels/28/ba/d5/a9e65abc786cf28af9f1fe4e73112f682b62b62564de9e9a8c
Successfully built ont-remora
Installing collected packages: tabulate, pytz, pysam, progressbar33, mappy, flatbuffers, fast-ctc-decode, wheel, urllib3, typing-extensions, tqdm, toml, threadpoolctl, six, pyparsing, pycparser, protobuf, numpy, more-itertools, joblib, iso8601, idna, chardet, certifi, torch, scipy, requests, python-dateutil, pyarrow, parasail, packaging, onnxruntime, onnx, h5py, cffi, thop, scikit-learn, pod5-format, pandas, ont-koi, ont-fast5-api, pod5-format-tools, ont-remora, ont-bonito
  Running setup.py install for progressbar33 ... done
  Running setup.py install for mappy ... done
  Running setup.py install for ont-bonito ... done
Successfully installed certifi-2022.5.18.1 cffi-1.15.0 chardet-4.0.0 fast-ctc-decode-0.3.2 flatbuffers-2.0 h5py-3.7.0 idna-2.10 iso8601-1.0.2 joblib-1.1.0 mappy-2.24 more-itertools-8.13.0 numpy-1.21.6 onnx-1.11.0 onnxruntime-1.11.0 ont-bonito-0.5.3 ont-fast5-api-3.3.0 ont-koi-0.0.9 ont-remora-1.1.0 packaging-21.3 pandas-1.3.5 parasail-1.2 pod5-format-0.0.14 pod5-format-tools-0.0.14 progressbar33-2.4 protobuf-4.21.1 pyarrow-7.0.0 pycparser-2.21 pyparsing-3.0.9 pysam-0.18.0 python-dateutil-2.8.2 pytz-2022.1 requests-2.25.1 scikit-learn-1.0.2 scipy-1.7.3 six-1.16.0 tabulate-0.8.9 thop-0.0.31.post2005241907 threadpoolctl-3.1.0 toml-0.10.2 torch-1.11.0 tqdm-4.64.0 typing-extensions-4.2.0 urllib3-1.26.9 wheel-0.37.1
(bonito-0.5.3) hasindu@genometech-gpgpu:~/scratch/short_read/PQXV22225$ bonito basecaller dna_r10.4_e8.1_sup@v3.4 PQXV22225/77_cellfree_plasma/20220530_1139_5E_PAI13493_29dbe22d/ --modified-bases 5mC --reference  /genome/hg38noAlt.idx >    basecalls_with_mods.bam
Traceback (most recent call last):
  File "/install/bonito-0.5.3/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito==0.5.3', 'console_scripts', 'bonito')()
  File "/install/bonito-0.5.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/install/bonito-0.5.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/install/bonito-0.5.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/install/bonito-0.5.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/install/bonito-0.5.3/lib/python3.7/site-packages/bonito/__init__.py", line 2, in <module>
    from bonito.cli import basecaller, train, evaluate, view, convert, download, export
  File "/install/bonito-0.5.3/lib/python3.7/site-packages/bonito/cli/basecaller.py", line 17, in <module>
    from bonito.io import CTCWriter, Writer, biofmt
  File "/install/bonito-0.5.3/lib/python3.7/site-packages/bonito/io.py", line 21, in <module>
    from bonito.util import mean_qscore_from_qstring
  File "/install/bonito-0.5.3/lib/python3.7/site-packages/bonito/util.py", line 18, in <module>
    import koi.lstm
  File "/install/bonito-0.5.3/lib/python3.7/site-packages/koi/lstm.py", line 3, in <module>
    from _runtime import lib
ImportError: /install/bonito-0.5.3/lib/python3.7/site-packages/_runtime.abi3.so: undefined symbol: host_run_lstm_fwd96
```

**Comment by iiSeymour** [comment]
I think this looks like a pip/wheel issues.

> Using legacy 'setup.py install' for ont-bonito, since package 'wheel' is not installed.

Can you try upgrading pip and install wheel in your virtualenv.

```
$ pip install --upgrade pip
$ pip install wheel
$ pip install --upgrade --force-reinstall ont-bonito
```

**Comment by hasindu2008** [comment]
Unfortunately the same issue :(  
Anyway, I think Dorado is soon going to support Remora as I remembered being told in London Calling - I could give Romara a go then.

**Comment by iiSeymour** [comment]
I can now reproduce this and it's only the Python 3.7 koi wheel that is affected - should have a fix soon.

**Comment by iiSeymour** [comment]
New wheels have been pushed and depended on 3c8294bef06d0cf6a163ff6ac8e0ddaef1be0b53 - py3.7 should be sorted now.
