### ISSUE TITLE
RuntimeError: Link iteration failed (incorrect metadatda checksum after all read attempts)

### ISSUE THREAD

**Issue by t-a-m-i** [nanoporetech/bonito#264]
Hey everyone, 

According to MinKnow 1.12 Million reads were generated during my last sequencing run. However, when I try to basecall them using Bonito everything works fine up until about 790k reads. Then it just stops and produces the following error: 

bonito basecaller dna_r9.4.1_e8_sup@v3.3 ~/Data/Nanopore/PC439_V1/fast5/ >PC439_bonito_basecall.fastq
> loading model dna_r9.4.1_e8_sup@v3.3
> outputting unaligned fastq
> calling: 787897 reads [7:22:18, 28.71 reads/s]Exception in thread Thread-1:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/jok/.local/lib/python3.8/site-packages/bonito/fast5.py", line 248, in get_read_ids
    ids = [(filename, rid) for rid in f5_fh.get_read_ids()]
  File "/home/jok/.local/lib/python3.8/site-packages/ont_fast5_api/multi_fast5.py", line 31, in get_read_ids
    return [group_name[5:] for group_name in self.handle if group_name.startswith('read_')]
  File "/home/jok/.local/lib/python3.8/site-packages/ont_fast5_api/multi_fast5.py", line 31, in <listcomp>
    return [group_name[5:] for group_name in self.handle if group_name.startswith('read_')]
  File "/home/jok/.local/lib/python3.8/site-packages/h5py/_hl/group.py", line 433, in __iter__
    for x in self.id.__iter__():
  File "h5py/h5g.pyx", line 126, in h5py.h5g.GroupIter.__next__
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5l.pyx", line 316, in h5py.h5l.LinkProxy.iterate
RuntimeError: Link iteration failed (incorrect metadatda checksum after all read attempts)
"""

>The above exception was the direct cause of the following exception:

>Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/jok/.local/lib/python3.8/site-packages/bonito/multiprocessing.py", line 110, in run
    for item in self.iterator:
  File "/home/jok/.local/lib/python3.8/site-packages/bonito/crf/basecall.py", line 59, in <genexpr>
    chunks = thread_iter(
  File "/home/jok/.local/lib/python3.8/site-packages/bonito/fast5.py", line 281, in get_reads
    for job in chain(pool.imap(get_filtered_reads, reads)):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
>RuntimeError: Link iteration failed (incorrect metadatda checksum after all read attempts)
> calling: 787952 reads [7:22:32, 33.82 reads/s]

Even though it says "calling" in the very end, the program stays stuck and doesn´t basecall any more reads. 
Could it be that the issue are corrupted fast5 files and if so how can I find them and remove from my dataset? 

Thank you all in advance for helping! 
Tamara

**Comment by iiSeymour** [comment]
Hey @t-a-m-i 

There appears to be a bad fast5 in your input. I've just pushed fa56de1 on [this branch](https://github.com/nanoporetech/bonito/tree/handle-bad-fast5) - are you able to test this resolves the issue?
