### ISSUE TITLE
AttributeError when making predictions

### ISSUE THREAD

**Issue by dberma15** [nanoporetech/bonito#279]
I'm trying to make predictions on new data, but I'm getting the following error: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bermads1/anaconda3/envs/pytorch_test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/bermads1/anaconda3/envs/pytorch_test/lib/python3.9/site-packages/bonito/crf/model.py", line 166, in forward
    return self.encoder(x)
  File "/home/bermads1/anaconda3/envs/pytorch_test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/bermads1/anaconda3/envs/pytorch_test/lib/python3.9/site-packages/bonito/nn.py", line 41, in forward
    return super().forward(x)
  File "/home/bermads1/anaconda3/envs/pytorch_test/lib/python3.9/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/bermads1/anaconda3/envs/pytorch_test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/bermads1/anaconda3/envs/pytorch_test/lib/python3.9/site-packages/bonito/nn.py", line 178, in forward
    y, h = self.rnn(x)
  File "/home/bermads1/anaconda3/envs/pytorch_test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 893, in _call_impl
    hook_result = hook(self, input, result)
  File "/home/bermads1/anaconda3/envs/pytorch_test/lib/python3.9/site-packages/torchsummary/torchsummary.py", line 22, in hook
    summary[m_key]["output_shape"] = [
  File "/home/bermads1/anaconda3/envs/pytorch_test/lib/python3.9/site-packages/torchsummary/torchsummary.py", line 23, in <listcomp>
    [-1] + list(o.size())[1:] for o in output
AttributeError: 'tuple' object has no attribute 'size'

The model is dna_r9.4.1@v3.1.toml
inputs.shape  is (batch_size, 1, sequence length)
model(inputs)

**Comment by dberma15** [comment]
I think I solve the problem. It was a problem. There was a bad value in the data. But I'm still running into a problem of processing the data. 

If I have a dummy model and data:
```
from bonito.util import load_symbol
import toml
import numpy as np
import torch

config_file= 'config/dna_r9.4.1@v3.1.toml'
configs = toml.load(config_file)
model2 = load_symbol(configs, "Model")(configs)

#inputs = np.load("inputs.npy")
inputs2 = torch.rand((5,1,5000))

output = model2(inputs2)

```
output.shape is torch.Size((1000, 5, 5120). Why isn't one of the dimensions 5, matching the label size for dna_r9.4.1@v3.1.toml?

**Comment by dberma15** [comment]
Closing because the issue was a result of an error in the data. However, a new issue was created to address a subsequent question.
