### ISSUE TITLE
Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False

### ISSUE THREAD

**Issue by rckeerthivasan** [nanoporetech/bonito#287]
Hi, 

I have previously installed bonito successfully and did a successful run. Currently, I am trying to run a new sample using the same commands as before, but I am facing new errors. I am running bonito on HPC with gpu availability. Is there any obvious thing that I am missing?

Thank you for your time, 
Ken. 

I use the command: `bonito basecaller dna_r9.4.1 ../fast5/fast5_pass/barcode01/ > all.fasta`
and this is the error: 
```
> loading model
Traceback (most recent call last):
  File "/home/kenrc/miniconda3/envs/bonito_july_2022.v6/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito', 'console_scripts', 'bonito')())
  File "/project/jcreminslab/kenrc_projects/softwares/bonito.gpu.3/bonito/bonito/__init__.py", line 39, in main
    args.func(args)
  File "/project/jcreminslab/kenrc_projects/softwares/bonito.gpu.3/bonito/bonito/cli/basecaller.py", line 28, in main
    model = load_model(args.model_directory, args.device, weights=int(args.weights))
  File "/project/jcreminslab/kenrc_projects/softwares/bonito.gpu.3/bonito/bonito/util.py", line 286, in load_model
    state_dict = torch.load(weights, map_location=device)
  File "/home/kenrc/miniconda3/envs/bonito_july_2022.v6/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/kenrc/miniconda3/envs/bonito_july_2022.v6/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "/home/kenrc/miniconda3/envs/bonito_july_2022.v6/lib/python3.7/site-packages/torch/serialization.py", line 665, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/kenrc/miniconda3/envs/bonito_july_2022.v6/lib/python3.7/site-packages/torch/serialization.py", line 740, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/home/kenrc/miniconda3/envs/bonito_july_2022.v6/lib/python3.7/site-packages/torch/serialization.py", line 156, in default_restore_location
    result = fn(storage, location)
  File "/home/kenrc/miniconda3/envs/bonito_july_2022.v6/lib/python3.7/site-packages/torch/serialization.py", line 132, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/kenrc/miniconda3/envs/bonito_july_2022.v6/lib/python3.7/site-packages/torch/serialization.py", line 116, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Comment by vellamike** [comment]
It looks like pytorch is seeing no GPU. Can you provide some details about your HPC setup - GPU, OS, NVIDIA driver version etc?

**Comment by rckeerthivasan** [comment]
these are the details: 

1) 19 Dell C6420 Quad node systems (76 compute nodes/6080 cores total)
 All nodes run CentOS v7.8
 80 CPU cores per node (with hyper-threading turned on)
 256 GB or 512 GB of RAM per node
 56 GB/s EDR or 100 GB/s FDR InfiniBand connection to the HPC filesystem

2) 1 Dell R940 big memory system with 1.5 TB RAM, 96 CPU cores, 10 GB/s Ethernet and 100 GB/s FDR InfiniBand connection to HPC filesystem

3) 2 GPU nodes each with 1x Nvidia Tesla P100 GPU card, 512 GB RAM, 88 CPU cores, 10 GB/s Ethernet and 100 GB/s FDR InfiniBand connection to HPC filesystem

4) 4.2 Petabytes of IBM Spectrum Scale (GPFS) Disk Storage (2 tiers, no backup)

5) 1.3 Petabytes of mirrored archive tape storage

6) Platform LSF job scheduling system

**Comment by vellamike** [comment]
> 2 GPU nodes each with 1x Nvidia Tesla P100 GPU card, 512 GB RAM, 88 CPU cores, 10 GB/s Ethernet and 100 GB/s FDR InfiniBand connection to HPC filesystem


This might be the problem. It's quite an old GPU we haven't tested on it in a long time. Can you run `nvidia-smi` on the node and let me know what it reports.

**Comment by vellamike** [comment]
Nothing seems obviously wrong. 

As a sanity test can you open a python terminal and type:

```
import torch
print(torch.__version__)
print(torch.cuda.is_available())
```

**Comment by rckeerthivasan** [comment]
```
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.4.0
>>> print(torch.cuda.is_available())
False
>>>
```

**Comment by vellamike** [comment]
1. How did you install bonito?
2. Can you confirm the torch import above is the one from the same environment as your bonito install (Conda/Venv /bare metal etc).

**Comment by vellamike** [comment]
PyTorch 1.4 is quite a few releases old (Jan 2020) so something seems off about your setup to me. Can you install Bonito in a venv using the PyPi release:

```
$ pip install --upgrade pip
$ pip install ont-bonito
```

**Comment by rckeerthivasan** [comment]
I created a new environment and tried to install as suggested. 

the commands I used are

```
conda create -n bonito_v18 python=3.7.3
conda activate bonito_v18 
pip install --upgrade pip
pip install ont-bonito
```

Although it seems that bonito is installed, I got these errors

```
error: [Errno 2] No such file or directory: 'build/bdist.linux-x86_64/wheel/ont_bonito-0.5.3.dist-info/dependency_links.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ont-bonito
  Running setup.py clean for ont-bonito
  Building wheel for ont-remora (pyproject.toml) ... done
  Created wheel for ont-remora: filename=ont_remora-1.1.0-cp37-cp37m-linux_x86_64.whl size=43541108 sha256=b7dd3bfbc38b0414928b5aa4bae732cef5eed6159a1a6aecf066d3ea1ffff328
  Stored in directory: /home/kenrc/.cache/pip/wheels/28/ba/d5/a9e65abc786cf28af9f1fe4e73112f682b62b62564de9e9a8c
Successfully built ont-remora
Failed to build ont-bonito
Installing collected packages: pytz, pysam, progressbar33, mappy, flatbuffers, fast-ctc-decode, urllib3, typing-extensions, tqdm, toml, threadpoolctl, tabulate, python-dateutil, pyparsing, pycparser, protobuf, numpy, more-itertools, joblib, iso8601, idna, chardet, torch, scipy, requests, pyarrow, parasail, pandas, packaging, onnxruntime, onnx, h5py, cffi, thop, scikit-learn, pod5-format, ont-koi, ont-fast5-api, pod5-format-tools, ont-remora, ont-bonito
  Attempting uninstall: torch
    Found existing installation: torch 1.4.0+cu100
    Uninstalling torch-1.4.0+cu100:
      Successfully uninstalled torch-1.4.0+cu100
  Running setup.py install for ont-bonito ... done
  DEPRECATION: ont-bonito was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. Discussion can be found at https://github.com/pypa/pip/issues/8368
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.5.0+cu100 requires torch==1.4.0, but you have torch 1.12.0 which is incompatible.
Successfully installed cffi-1.15.1 chardet-4.0.0 fast-ctc-decode-0.3.2 flatbuffers-2.0 h5py-3.7.0 idna-2.10 iso8601-1.0.2 joblib-1.1.0 mappy-2.24 more-itertools-8.13.0 numpy-1.21.6 onnx-1.12.0 onnxruntime-1.11.0 ont-bonito-0.5.3 ont-fast5-api-3.3.0 ont-koi-0.0.9 ont-remora-1.1.0 packaging-21.3 pandas-1.3.5 parasail-1.2 pod5-format-0.0.14 pod5-format-tools-0.0.14 progressbar33-2.4 protobuf-3.20.1 pyarrow-7.0.0 pycparser-2.21 pyparsing-3.0.9 pysam-0.18.0 python-dateutil-2.8.2 pytz-2022.1 requests-2.25.1 scikit-learn-1.0.2 scipy-1.7.3 tabulate-0.8.10 thop-0.1.1.post2207130030 threadpoolctl-3.1.0 toml-0.10.2 torch-1.12.0 tqdm-4.64.0 typing-extensions-4.3.0 urllib3-1.26.10
```

Then, I run bonito by running `bonito`, I get
```

/home/kenrc/miniconda3/envs/bonito_v18/lib/python3.7/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/home/kenrc/miniconda3/envs/bonito_v18/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito==0.5.3', 'console_scripts', 'bonito')())
  File "/home/kenrc/miniconda3/envs/bonito_v18/lib/python3.7/site-packages/pkg_resources/__init__.py", line 485, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/kenrc/miniconda3/envs/bonito_v18/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/home/kenrc/miniconda3/envs/bonito_v18/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2458, in load
    return self.resolve()
  File "/home/kenrc/miniconda3/envs/bonito_v18/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2464, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kenrc/miniconda3/envs/bonito_v18/lib/python3.7/site-packages/bonito/__init__.py", line 2, in <module>
    from bonito.cli import basecaller, train, evaluate, view, convert, download, export
  File "/home/kenrc/miniconda3/envs/bonito_v18/lib/python3.7/site-packages/bonito/cli/basecaller.py", line 17, in <module>
    from bonito.io import CTCWriter, Writer, biofmt
  File "/home/kenrc/miniconda3/envs/bonito_v18/lib/python3.7/site-packages/bonito/io.py", line 21, in <module>
    from bonito.util import mean_qscore_from_qstring
  File "/home/kenrc/miniconda3/envs/bonito_v18/lib/python3.7/site-packages/bonito/util.py", line 18, in <module>
    import koi.lstm
  File "/home/kenrc/miniconda3/envs/bonito_v18/lib/python3.7/site-packages/koi/lstm.py", line 3, in <module>
    from _runtime import lib
ImportError: /home/kenrc/miniconda3/envs/bonito_v18/lib/python3.7/site-packages/_runtime.abi3.so: undefined symbol: host_run_lstm_fwd96
```

**Comment by vellamike** [comment]
> Since we don't have CUDA 10.2 on HPC, I have installed seqdist by changing the settings.ini file as described in one of the issues (https://github.com/nanoporetech/bonito/issues/60). These are the commands I originally used.

seqdist is no longer a requirement. You don't need to worry about this, you don't need CUDA on your system either - just an NVIDIA driver.

There's a couple of things going on here, firstly the import error, I haven't installed in Conda before, I would use virtualenv (at least to test it out on your system) as this is known to work.

More seriously:

```
/home/kenrc/miniconda3/envs/bonito_v18/lib/python3.7/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: **The NVIDIA driver on your system is too old** (found version 10000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
```

This suggests to me that you will need your sysadmin will need to upgrade the Nvidia driver. 410.104 is from 2019 so unfortunately it's well due an upgrade.

**Comment by rckeerthivasan** [comment]
Thank you Mike for your time and suggestions. I will be sure to inform my sys admin to update these Nvidia drivers. In the mean time, I have tried installing using python virtual environment as follow:


```
module load python/3.6.3 
python3 -m venv venv3
source venv3/bin/activate

pip install --upgrade pip
# installed version 21.3.1, but 22.1.2 is available

pip install ont-bonito
```

This installation is definitely unsuccessful. Am I missing something?
```

Building wheels for collected packages: ont-remora
  Building wheel for ont-remora (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /project/jcreminslab/kenrc_projects/softwares.3/bonito.mikevella/venv3/bin/python3 /project/jcreminslab/kenrc_projects/softwares.3/bonito.mikevella/venv3/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpadtmjt5b
       cwd: /tmp/pip-install-4ka0gf7n/ont-remora_801e382fefc5470496ad71e6ccc616ba
  Complete output (129 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/remora
  copying src/remora/__init__.py -> build/lib.linux-x86_64-3.6/remora
  copying src/remora/activations.py -> build/lib.linux-x86_64-3.6/remora
  copying src/remora/constants.py -> build/lib.linux-x86_64-3.6/remora
  copying src/remora/data_chunks.py -> build/lib.linux-x86_64-3.6/remora
  copying src/remora/inference.py -> build/lib.linux-x86_64-3.6/remora
  copying src/remora/log.py -> build/lib.linux-x86_64-3.6/remora
  copying src/remora/main.py -> build/lib.linux-x86_64-3.6/remora
  copying src/remora/model_util.py -> build/lib.linux-x86_64-3.6/remora
  copying src/remora/parsers.py -> build/lib.linux-x86_64-3.6/remora
  copying src/remora/prepare_train_data.py -> build/lib.linux-x86_64-3.6/remora
  copying src/remora/train_model.py -> build/lib.linux-x86_64-3.6/remora
  copying src/remora/util.py -> build/lib.linux-x86_64-3.6/remora
  running egg_info
  writing src/ont_remora.egg-info/PKG-INFO
  writing dependency_links to src/ont_remora.egg-info/dependency_links.txt
  writing entry points to src/ont_remora.egg-info/entry_points.txt
  writing requirements to src/ont_remora.egg-info/requires.txt
  writing top-level names to src/ont_remora.egg-info/top_level.txt
  reading manifest file 'src/ont_remora.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE.txt'
  writing manifest file 'src/ont_remora.egg-info/SOURCES.txt'
  copying src/remora/encoded_kmers.pyx -> build/lib.linux-x86_64-3.6/remora
  creating build/lib.linux-x86_64-3.6/remora/trained_models
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/fast
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/fast/0.0.0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/fast/0.0.0/5hmc_5mc
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/fast/0.0.0/5hmc_5mc/CG
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/fast/0.0.0/5hmc_5mc/CG/v0
  copying src/remora/trained_models/dna_r10.4_e8.1/fast/0.0.0/5hmc_5mc/CG/v0/modbase_model.onnx -> build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/fast/0.0.0/5hmc_5mc/CG/v0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/fast/0.0.0/5mc
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/fast/0.0.0/5mc/CG
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/fast/0.0.0/5mc/CG/v0
  copying src/remora/trained_models/dna_r10.4_e8.1/fast/0.0.0/5mc/CG/v0/modbase_model.onnx -> build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/fast/0.0.0/5mc/CG/v0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/hac
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/hac/0.0.0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/hac/0.0.0/5hmc_5mc
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/hac/0.0.0/5hmc_5mc/CG
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/hac/0.0.0/5hmc_5mc/CG/v0
  copying src/remora/trained_models/dna_r10.4_e8.1/hac/0.0.0/5hmc_5mc/CG/v0/modbase_model.onnx -> build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/hac/0.0.0/5hmc_5mc/CG/v0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/hac/0.0.0/5mc
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/hac/0.0.0/5mc/CG
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/hac/0.0.0/5mc/CG/v0
  copying src/remora/trained_models/dna_r10.4_e8.1/hac/0.0.0/5mc/CG/v0/modbase_model.onnx -> build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/hac/0.0.0/5mc/CG/v0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/sup
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/sup/0.0.0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/sup/0.0.0/5hmc_5mc
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/sup/0.0.0/5hmc_5mc/CG
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/sup/0.0.0/5hmc_5mc/CG/v0
  copying src/remora/trained_models/dna_r10.4_e8.1/sup/0.0.0/5hmc_5mc/CG/v0/modbase_model.onnx -> build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/sup/0.0.0/5hmc_5mc/CG/v0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/sup/0.0.0/5mc
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/sup/0.0.0/5mc/CG
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/sup/0.0.0/5mc/CG/v0
  copying src/remora/trained_models/dna_r10.4_e8.1/sup/0.0.0/5mc/CG/v0/modbase_model.onnx -> build/lib.linux-x86_64-3.6/remora/trained_models/dna_r10.4_e8.1/sup/0.0.0/5mc/CG/v0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/fast
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/fast/0.0.0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/fast/0.0.0/5mc
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/fast/0.0.0/5mc/CG
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/fast/0.0.0/5mc/CG/v0
  copying src/remora/trained_models/dna_r9.4.1_e8.1/fast/0.0.0/5mc/CG/v0/modbase_model.onnx -> build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/fast/0.0.0/5mc/CG/v0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/hac
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/hac/0.0.0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/hac/0.0.0/5mc
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/hac/0.0.0/5mc/CG
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/hac/0.0.0/5mc/CG/v0
  copying src/remora/trained_models/dna_r9.4.1_e8.1/hac/0.0.0/5mc/CG/v0/modbase_model.onnx -> build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/hac/0.0.0/5mc/CG/v0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/sup
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/sup/0.0.0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/sup/0.0.0/5mc
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/sup/0.0.0/5mc/CG
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/sup/0.0.0/5mc/CG/v0
  copying src/remora/trained_models/dna_r9.4.1_e8.1/sup/0.0.0/5mc/CG/v0/modbase_model.onnx -> build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8.1/sup/0.0.0/5mc/CG/v0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/fast
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/fast/0.0.0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/fast/0.0.0/5hmc_5mc
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/fast/0.0.0/5hmc_5mc/CG
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/fast/0.0.0/5hmc_5mc/CG/v0
  copying src/remora/trained_models/dna_r9.4.1_e8/fast/0.0.0/5hmc_5mc/CG/v0/modbase_model.onnx -> build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/fast/0.0.0/5hmc_5mc/CG/v0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/fast/0.0.0/5mc
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/fast/0.0.0/5mc/CG
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/fast/0.0.0/5mc/CG/v0
  copying src/remora/trained_models/dna_r9.4.1_e8/fast/0.0.0/5mc/CG/v0/modbase_model.onnx -> build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/fast/0.0.0/5mc/CG/v0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/hac
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/hac/0.0.0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/hac/0.0.0/5hmc_5mc
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/hac/0.0.0/5hmc_5mc/CG
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/hac/0.0.0/5hmc_5mc/CG/v0
  copying src/remora/trained_models/dna_r9.4.1_e8/hac/0.0.0/5hmc_5mc/CG/v0/modbase_model.onnx -> build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/hac/0.0.0/5hmc_5mc/CG/v0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/hac/0.0.0/5mc
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/hac/0.0.0/5mc/CG
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/hac/0.0.0/5mc/CG/v0
  copying src/remora/trained_models/dna_r9.4.1_e8/hac/0.0.0/5mc/CG/v0/modbase_model.onnx -> build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/hac/0.0.0/5mc/CG/v0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/sup
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/sup/0.0.0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/sup/0.0.0/5hmc_5mc
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/sup/0.0.0/5hmc_5mc/CG
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/sup/0.0.0/5hmc_5mc/CG/v0
  copying src/remora/trained_models/dna_r9.4.1_e8/sup/0.0.0/5hmc_5mc/CG/v0/modbase_model.onnx -> build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/sup/0.0.0/5hmc_5mc/CG/v0
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/sup/0.0.0/5mc
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/sup/0.0.0/5mc/CG
  creating build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/sup/0.0.0/5mc/CG/v0
  copying src/remora/trained_models/dna_r9.4.1_e8/sup/0.0.0/5mc/CG/v0/modbase_model.onnx -> build/lib.linux-x86_64-3.6/remora/trained_models/dna_r9.4.1_e8/sup/0.0.0/5mc/CG/v0
  running build_ext
  cythoning src/remora/encoded_kmers.pyx to src/remora/encoded_kmers.c
  building 'remora.encoded_kmers' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  creating build/temp.linux-x86_64-3.6/src/remora
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/project/jcreminslab/kenrc_projects/softwares.3/bonito.mikevella/venv3/include -I/usr/include/python3.6m -c src/remora/encoded_kmers.c -o build/temp.linux-x86_64-3.6/src/remora/encoded_kmers.o -std=c99
  src/remora/encoded_kmers.c:6:20: fatal error: Python.h: No such file or directory
   #include "Python.h"
                      ^
  compilation terminated.
  /usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'use_pyscaffold'
    warnings.warn(msg)
  /tmp/pip-build-env-kyaehrp9/overlay/lib/python3.6/site-packages/setuptools/dist.py:726: UserWarning: Usage of dash-separated 'long-description' will not be supported in future versions. Please use the underscore name 'long_description' instead
    % (opt, underscore_opt)
  /tmp/pip-build-env-kyaehrp9/overlay/lib/python3.6/site-packages/setuptools/dist.py:726: UserWarning: Usage of dash-separated 'long-description-content-type' will not be supported in future versions. Please use the underscore name 'long_description_content_type' instead
    % (opt, underscore_opt)
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ont-remora
Failed to build ont-remora
ERROR: Could not build wheels for ont-remora, which is required to install pyproject.toml-based projects

```

Since I don't need Remora, can I bypass and just install bonito? 

Thank you again.

**Comment by vellamike** [comment]
Can you use python >=3.7 ?

**Comment by rckeerthivasan** [comment]
Thank you for your time and helpful insights. 

I have tried installing with python 3.9.1 using the commands in two different virtual envs. 

```
module load python/3.9.1
python3 -m venv venv3.6
source venv3.6/bin/activate
pip install --upgrade pip
pip install ont-bonito
```

```
module load python/3.9.1
python3 -m venv venv3.6
source venv3.6/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
python setup.py develop
```

Now, when I run bonito by typing the command, I get `bonito`, I see this error. it is clear that NVIDIA driver has to be updated. alternatively, it is also suggesting to install pytorch from the website. 
```
venv3.6/lib/python3.9/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
usage: bonito [-h] [-v] {basecaller,train,evaluate,view,convert,download,export} ...
bonito: error: the following arguments are required: command
```

I selected the options as shown in the figure and it gave a command and I executed them. I still got the same error. Could you provide any insights? 
<img width="837" alt="Screen Shot 2022-07-19 at 3 20 56 PM" src="https://user-images.githubusercontent.com/25299779/179831704-2dda2f49-689e-4efa-98dc-5c8095d8b1a2.png">

**Comment by vellamike** [comment]
I'm not at all at all sure downgrading PyTorch will work, this hasn't been tested.

Thinking about this further, Bonito uses instructions which are not available for P100, so I'm afraid you really need a more modern GPU (Volta and beyond) to run it.

Sorry I can't be of more help.

**Comment by davidnewman02** [comment]
Closing as issue is out of scope - lack of supported GPU
