### ISSUE TITLE
min_qscore in CTCWriter class in v.0.6.0

### ISSUE THREAD

**Issue by dottorscaglione** [nanoporetech/bonito#302]
Dear @iiSeymour,
with the last version 0.6.0 I'm getting an error since it seems to me that when the save-ctc is invoked and therefore the CTCWriter class, but this last does not handle the min_qscore arg that is passed.

```
bonito basecaller dna_r10.4_e8.1_fast@v3.4 fast5_pass/ --reference ../../../genomes-trainings/Zm-B73-REFERENCE-GRAMENE-4.0.mmi --save-ctc --min-qscore 9 > bonito_basecall_10.4_e8.1_fast/B73_v4.bam 
> reading fast5
> outputting aligned bam
> loading model dna_r10.4_e8.1_fast@v3.4
> loading reference
Traceback (most recent call last):                                                                  
  File "/home/nanoporelab/.local/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/home/nanoporelab/.local/lib/python3.8/site-packages/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/nanoporelab/.local/lib/python3.8/site-packages/bonito/cli/basecaller.py", line 144, in main
    writer = ResultsWriter(
TypeError: __init__() got an unexpected keyword argument 'min_qscore'
```

**Comment by iiSeymour** [comment]
Thanks @dottorscaglione - I've just pushed a fixed for this https://github.com/nanoporetech/bonito/commit/02962268262b9bba0447ddc3f764ddf78edd4db4.
