### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by mezoderma** [nanoporetech/bonito#306]
Hello,

I tried to run bonito on server. To be sure I validate it with cpu parametr, but anyway got the same error:

[ibrsnk@head02 ~]$ ~/.local/bin/bonito basecaller --device cpu dna_r10.4_e8.1_sup@v3.4 ~/fast5/ > basecalls.bam
Traceback (most recent call last):
  File "/home/ibrsnk/.local/bin/bonito", line 5, in <module>
    from bonito import main
  File "/home/ibrsnk/.local/lib/python3.8/site-packages/bonito/__init__.py", line 2, in <module>
    from bonito.cli import basecaller, train, evaluate, view, convert, download, export
  File "/home/ibrsnk/.local/lib/python3.8/site-packages/bonito/cli/basecaller.py", line 18, in <module>
    from bonito.mod_util import call_mods, load_mods_model
  File "/home/ibrsnk/.local/lib/python3.8/site-packages/bonito/mod_util.py", line 6, in <module>
    from remora.model_util import load_model
  File "/home/ibrsnk/.local/lib/python3.8/site-packages/remora/model_util.py", line 18, in <module>
    from sklearn.metrics import confusion_matrix
  File "/home/tools/python/Python-3.8.2/lib/python3.8/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/tools/python/Python-3.8.2/lib/python3.8/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/tools/python/Python-3.8.2/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 24, in <module>
    from .murmurhash import murmurhash3_32
ImportError: dlopen: cannot load any more object with static TLS

How to fix it?

Thank you in advantion,
Ilya

**Comment by iiSeymour** [comment]
@mezoderma this is an issue with sklearn https://github.com/scikit-learn/scikit-learn/issues/14485
