### ISSUE TITLE
Bonito with modified base rerio model

### ISSUE THREAD

**Issue by vivekbhr** [nanoporetech/bonito#312]
Hello

I am trying to call modified all-C context basecalling on our pore R941 data. I tried running bonito with the flipflop rerio model [res_dna_r941_prom_modbases_5mC_v001](https://github.com/nanoporetech/rerio/blob/master/basecall_models/res_dna_r941_prom_modbases_5mC_v001) but can not get it to work.

The command below fails:

```
bonito basecaller --reference ref_genome.fa \
--modified-base-model rerio/basecall_models/res_dna_r941_prom_modbases_5mC_v001 \
dna_r9.4.1_e8_hac@v3.3 fast5_pass/ > out.bam 
```
Error below:

```
> reading fast5
> outputting aligned bam
> loading model dna_r9.4.1_e8_hac@v3.3
> loading modified base model
Traceback (most recent call last):
  File "/hpc/test/programs/miniconda3/envs/ont/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/hpc/test/programs/miniconda3/envs/ont/lib/python3.10/site-packages/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/hpc/test/programs/miniconda3/envs/ont/lib/python3.10/site-packages/bonito/cli/basecaller.py", line 75, in main
    mods_model = load_mods_model(
  File "/hpc/test/programs/miniconda3/envs/ont/lib/python3.10/site-packages/bonito/mod_util.py", line 55, in load_mods_model
    return load_model(model_path, quiet=True, device=device)
  File "/hpc/test/programs/miniconda3/envs/ont/lib/python3.10/site-packages/remora/model_util.py", line 499, in load_model
    return load_onnx_model(model_filename, device, quiet=quiet)
  File "/hpc/test/programs/miniconda3/envs/ont/lib/python3.10/site-packages/remora/model_util.py", line 350, in load_onnx_model
    model_sess = ort.InferenceSession(
  File "/hpc/test/programs/miniconda3/envs/ont/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/hpc/test/programs/miniconda3/envs/ont/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /hpc/test/programs/rerio/basecall_models/res_dna_r941_prom_modbases_5mC_v001 failed:Protobuf parsing failed.
```

The command below reverts to using the 5mC remora model in CG context only:

```
bonito basecaller --reference ref_genome.fa --modified-bases 5mC \
--modified-base-model rerio/basecall_models/res_dna_r941_prom_modbases_5mC_v001 \
dna_r9.4.1_e8_hac@v3.3 fast5_pass/ > out.bam 
```

Do I understand correctly that this model is not compatible with bonito? Is there a way to convert this to bonito compatible model? or any other suggestion to try bonito in all-C context for pore R9.4.1 ?

Best,
Vivek

**Comment by clock-matt** [comment]
I had the same issue, my command was:

bonito basecaller dna_r10.4.1_e8.2_400bps_sup@v3.5.2 data/OM2/ --modified-base-model rerio/remora_models/5mC_all_context_sup_r1041_e82 --reference ref.mmi --recursive --device cuda:0 --modified-device cuda:0 --verbose > bonito_out/OM2_mods.bam

The error message was:
> reading fast5
> outputting aligned bam
> loading model dna_r10.4.1_e8.2_400bps_sup@v3.5.2
> model basecaller params: {'batchsize': 96, 'chunksize': 10000, 'overlap': 500,
 'quantize': None}
> loading modified base model
Traceback (most recent call last):
  File "/home/matthew/anaconda3/envs/bonito/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/home/matthew/anaconda3/envs/bonito/lib/python3.10/site-packages/bonito/
__init__.py", line 34, in main
    args.func(args)
  File "/home/matthew/anaconda3/envs/bonito/lib/python3.10/site-packages/bonito/
cli/basecaller.py", line 75, in main
    mods_model = load_mods_model(
  File "/home/matthew/anaconda3/envs/bonito/lib/python3.10/site-packages/bonito/mod_util.py", line 55, in load_mods_model
    return load_model(model_path, quiet=True, device=device)
  File "/home/matthew/anaconda3/envs/bonito/lib/python3.10/site-packages/remora/model_util.py", line 499, in load_model
    return load_onnx_model(model_filename, device, quiet=quiet)
  File "/home/matthew/anaconda3/envs/bonito/lib/python3.10/site-packages/remora/model_util.py", line 350, in load_onnx_model
    model_sess = ort.InferenceSession(
  File "/home/matthew/anaconda3/envs/bonito/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/matthew/anaconda3/envs/bonito/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from rerio/remora_models/5mC_all_context_sup_r1041_e82 failed:Protobuf parsing failed.

**Comment by marcus1487** [comment]
You are correct. The older basecaller integrated modified base models are not compatible with bonito. Bonito only supports the newer Remora models which are separated from the basecalling model (note that for the best performance Remora models should be run with the associated basecalling model, but the remora models can be applied independently from the basecalling model).
