### ISSUE TITLE
training error: not enough values to unpack (expected 4, got 0)

### ISSUE THREAD

**Issue by fangli80** [nanoporetech/bonito#340]
Hello, 
I'm trying to fine-tune bonito on my own data, but got the following error: 

```
> reading fast5
> outputting aligned sam
> loading model dna_r9.4.1_e8_hac@v3.3
> loading reference
> Chunks rejected from training data:                                                               
 - no_mapping: 886
 - low_accuracy0.99: 16271
 - low_coverage0.90: 1
> written ctc training data to /home/devdata/fangl/projects/tandem_repeat_detection/chm13/fast5/eichler/minion/20190125_CHM13_no10_13ug_1to12/20190125_CHM13_no10_13ug_1to12/20190125_1851_MN29101_FAK26323_f6aff12a/bonito/training/ctc-data
  - chunks.npy with shape (328,10000)
  - references.npy with shape (328,1123)
  - reference_lengths.npy shape (328)
> completed reads: 17497
> duration: 0:00:23
> samples per second 7.8E+06
> done
[loading model]
[using pretrained model dna_r9.4.1_e8_hac@v3.3]
[loading data]
[validation set not found: splitting training set]
[328/328]: 100%|##############################################################| [00:13, loss=0.0293]
Traceback (most recent call last):
  File "/home/fangl/data/anaconda3/envs/bonito/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/home/fangl/data/anaconda3/envs/bonito/lib/python3.8/site-packages/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/fangl/data/anaconda3/envs/bonito/lib/python3.8/site-packages/bonito/cli/train.py", line 101, in main
    trainer.fit(workdir, args.epochs, lr)
  File "/home/fangl/data/anaconda3/envs/bonito/lib/python3.8/site-packages/bonito/training.py", line 223, in fit
    val_loss, val_mean, val_median = self.validate_one_epoch()
  File "/home/fangl/data/anaconda3/envs/bonito/lib/python3.8/site-packages/bonito/training.py", line 183, in validate_one_epoch
    seqs, refs, accs, losses = zip(*(self.validate_one_step(batch) for batch in self.valid_loader))
ValueError: not enough values to unpack (expected 4, got 0)
```

My command is: 

```
#!/bin/bash
eval "$(conda shell.bash hook)"
conda activate bonito


fast5_dir=path/to/fast5
ref_fasta=path/to/chm13v2.0.fa
bonito_model_name=dna_r9.4.1_e8_hac@v3.3
out_dir=$fast5_dir/bonito

mkdir -p $out_dir
mkdir -p $out_dir/training/ctc-data
mkdir -p $out_dir/training/fine-tuned-model
bonito basecaller --recursive $bonito_model_name --save-ctc --reference $ref_fasta $fast5_dir > $out_dir/training/ctc-data/basecalls.sam
bonito train -f --epochs 1 --lr 5e-4 --pretrained $bonito_model_name --directory $out_dir/training/ctc-data/ $out_dir/training/fine-tuned-model/
```

Could you please help

**Comment by N-damo** [comment]
any update?

**Comment by chAwater** [comment]
@iiSeymour @aevansNP I think this is a **bug** caused by https://github.com/nanoporetech/bonito/commit/5bcd11e191d187295fe921f04dc46b1172724583 with 

https://github.com/nanoporetech/bonito/blob/5bcd11e191d187295fe921f04dc46b1172724583/bonito/data.py#L47-L52

and 

https://github.com/nanoporetech/bonito/blob/d36dfcae2b4da17e90869280949a29a74d17c4de/bonito/cli/train.py#L120

The default `--valid-chunks` is `0` making the `split` always be the length of training data, so the `valid_data` will be empty.

---

@fangli80 @N-damo You can bypass it by adding `--valid-chunks 128` in your command line (use 128 chunks for validation as an example).
