### ISSUE TITLE
Exception while running basecaller 

### ISSUE THREAD

**Issue by amansinha-sw** [nanoporetech/bonito#366]
I have installed bonito from source and the installation succeeded without any issue.
However when I am trying to run the basecaller, I am getting the below exception:

> reading fast5
> outputting unaligned fastq
> loading model ../bonito/models/dna_r9.4.1_e8_fast@v3.4/
> calling: 0 reads [00:00, ? reads/s]Exception in thread Thread-1:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/mnt/newNAS/home/otherLab/pcs02/Aman/bonito/venv3/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 649, in parse
    ret = self._build_naive(res, default)
  File "/mnt/newNAS/home/otherLab/pcs02/Aman/bonito/venv3/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 1235, in _build_naive
    naive = default.replace(**repl)
ValueError: year 1478286901 is out of range

The above exception was the direct cause of the following exception:
I have not been able to find a solution to this, and I am now facing the same issue despite installing directly from pip.

Please suggest a solution. Thanks.

**Comment by amansinha-sw** [comment]
I was able to run successfully by modifying the datetime logic in _parser.py
