### ISSUE TITLE
missing wheel package as requirement

### ISSUE THREAD

**Issue by lucacozzuto** [nanoporetech/bonito#5]
Dear developer,
I think wheel is missing in the requirements since without it the installation is not possible.

Thanks,

Luca

**Comment by iiSeymour** [comment]
Hey @lucacozzuto `wheel` is specified in the [requirements.txt](https://github.com/nanoporetech/bonito/blob/master/requirements.txt#L4) file.

Was this issue seen when following the quickstart and can you post the resulting error?

**Comment by lucacozzuto** [comment]
Hi!

when running pip install -r requirements.txt
I got:

```
Collecting toml==0.10.0
  Downloading https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting tqdm==4.31.1
  Downloading https://files.pythonhosted.org/packages/6c/4b/c38b5144cf167c4f52288517436ccafefe9dc01b8d1c190e18a6b154cd4a/tqdm-4.31.1-py2.py3-none-any.whl (48kB)
     |████████████████████████████████| 51kB 764kB/s 
Collecting torch==1.3.1
  Downloading https://files.pythonhosted.org/packages/88/95/90e8c4c31cfc67248bf944ba42029295b77159982f532c5689bcfe4e9108/torch-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (734.6MB)
     |████████████████████████████████| 734.6MB 12kB/s 
Collecting wheel==0.33.6
  Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
Collecting parasail==1.1.19
  Downloading https://files.pythonhosted.org/packages/a1/51/dfacc4be8e29d5df99700b7255abeae81f5381ed6520c46c041a596b7e9d/parasail-1.1.19.tar.gz (71kB)
     |████████████████████████████████| 81kB 3.8MB/s 
    ERROR: Command errored out with exit status 1:
     command: /nfs/users2/bi/lcozzuto/bonito/venv3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1e3degqr/parasail/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1e3degqr/parasail/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-1e3degqr/parasail/pip-egg-info
         cwd: /tmp/pip-install-1e3degqr/parasail/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1e3degqr/parasail/setup.py", line 18, in <module>
        from wheel.bdist_wheel import bdist_wheel as bdist_wheel_
    ModuleNotFoundError: No module named 'wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
thanks.

**Comment by iiSeymour** [comment]
Can you install `wheel` first with `pip install wheel` then try the `pip install -r requirements.txt`.

Strange as the output suggests you already have a copy of `wheel`. I will try and reproduce this.

```
Collecting wheel==0.33.6
  Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
```

**Comment by lucacozzuto** [comment]
Yes If I install wheel before it goes through (for this I thought that wheel was not in the requirements).

L

**Comment by iiSeymour** [comment]
I've added wheel to installation to the quickstart.

**Comment by iiSeymour** [comment]
Wheel was required prior to installing the requirements to build parasail but this is no longer the case since https://github.com/jeffdaily/parasail-python/issues/11
