### ISSUE TITLE
bonito run stopped on KeyError: 'Unable to open object (message not aligned)' - program does not exit properly

### ISSUE THREAD

**Issue by RaverJay** [nanoporetech/bonito#65]
Hi,

while running same bonito tests, this one got stuck after about 20 hours with:

```
bonito basecaller dna_r9.4.1 /data/fass2/reads/ont/corona_amplicon_test/RAW/20201016_FAO92019_Corona_amplicon_x10/20201016_FAO92019_Corona_amplicon_x10/20201016_FAO92019_Corona_amplicon_x10/20201016_1536_MN21435_FAO92019_4ca09abb/fast5/ > bonito_basecalls.fa

> loading model
> calling: 5405007 reads [20:55:28, 43.64 reads/s]Exception in thread Thread-1:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/fast5.py", line 114, in get_raw_data_for_read
    return Read(f5_fh.get_read(read_id), filename)
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/fast5.py", line 26, in __init__
    channel_info = read.handle[read.global_key + 'channel_id'].attrs
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/site-packages/h5py/_hl/group.py", line 298, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (message not aligned)'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/multiprocessing.py", line 181, in run
    for (k, v) in self.iterator:
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/crf/basecall.py", line 105, in <genexpr>
    stitched = ((read, _stitch(x)) for (read, x) in unbatchify(batches))
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/util.py", line 209, in <genexpr>
    for k, group in groupby(batches, itemgetter(0))
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/util.py", line 208, in <listcomp>
    (k, concat([v for (k, v) in group], dim))
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/util.py", line 203, in <genexpr>
    (k, select_range(v, start, end, dim))
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/crf/basecall.py", line 102, in <genexpr>
    (read, quantise_int8(compute_scores(model, batch)))
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/util.py", line 181, in batchify
    for k, v in items:
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/crf/basecall.py", line 99, in <genexpr>
    ((read, chunk(signal, chunksize, overlap, pad_start=True)) for (read, signal) in reads)
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/crf/basecall.py", line 95, in <genexpr>
    ((read, i), x) for read in reads
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/fast5.py", line 124, in get_reads
    for read in pool.imap(get_raw_data_for_read, job):
  File "/home/ya86gul/miniconda3/envs/bonito/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
KeyError: 'Unable to open object (message not aligned)'

> calling: 5405007 reads [20:55:41, 43.64 reads/s]
```

Console output stopped updating, terminal is unresponsive.
Not sure how this KeyError came to be. Bad fast5 file?

In any case, error handling in pool workers did not cause a proper program exit

Best

**Comment by iiSeymour** [comment]
Hey @RaverJay 

Yes, this looks like a bad Fast5 file to me. I'll get this handled for the next version, for now, you could do -

```patch
diff --git a/bonito/fast5.py b/bonito/fast5.py
index 426691e..23cf7b1 100644
--- a/bonito/fast5.py
+++ b/bonito/fast5.py
@@ -111,8 +111,10 @@ def get_raw_data_for_read(info):
     """
     filename, read_id = info
     with get_fast5_file(filename, 'r') as f5_fh:
-        return Read(f5_fh.get_read(read_id), filename)
-
+        try:
+            return Read(f5_fh.get_read(read_id), filename)
+        except:
+            return None
 
 def get_reads(directory, read_ids=None, skip=False, max_read_size=0, n_proc=1):
     """
@@ -127,4 +129,5 @@ def get_reads(directory, read_ids=None, skip=False, max_read_size=0, n_proc=1):
                         "> skipping long read %s (%s samples)\n" % (read.read_id, len(read.signal))
                     )
                     continue
-                yield read
+                if read is not None:
+                    yield read
`````

**Comment by iiSeymour** [comment]
Graceful clean up handled in latest version.
