### ISSUE TITLE
NotImplemented Error

### ISSUE THREAD

**Issue by mattdmem** [nanoporetech/bonito#66]
I'm trying to do some training but falling at the 1st hurdle... when I add --save-ctc to by basecaller command I get the following error.... tried with the pip version and the latest from the repo. Works fine without the ctc flag...

```
bonito basecaller --reference /media/x/be7a23c3-1f3c-4702-97a3-dfff75ed33c3/20201114/x-j.mmi --save-ctc bonito/models/dna_r9.4.1 /media/x/be7a23c3-1f3c-4702-97a3-dfff75ed33c3/20201114/x-j/dba2a168/fast5_pass
> loading model
> loading reference
Traceback (most recent call last):
  File "/home/x/.local/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/home/x/.local/lib/python3.5/site-packages/bonito/__init__.py", line 39, in main
    args.func(args)
  File "/home/x/.local/lib/python3.5/site-packages/bonito/cli/basecaller.py", line 47, in main
    min_accuracy=args.ctc_min_accuracy, min_coverage=args.ctc_min_coverage
  File "/home/x/.local/lib/python3.5/site-packages/bonito/crf/basecall.py", line 121, in ctc_data
    raise NotImplemented
TypeError: exceptions must derive from BaseException
```

**Comment by iiSeymour** [comment]
Hey @mattdmem 

We didn't get a `--save-ctc` pipeline implemented for the new CRF model in time for v0.3.0 but you can use the V0.2.X model to create a training set.

Just make sure you have the latest commits on master and download the v2 model first -

```shell
(venv3) $ bonito download --models
(venv3) $ bonito basecaller dna_r9.4.1@v2 --save-ctc --reference /media/x/be7a23c3-1f3c-4702-97a3-dfff75ed33c3/20201114/x-j.mmi /media/x/be7a23c3-1f3c-4702-97a3-dfff75ed33c3/20201114/x-j/dba2a168/fast5_pass
```

**Comment by mattdmem** [comment]
Thanks.. I now get this error (models downloaded)

```
git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

 python setup.py develop

bonito basecaller dna_r9.4.1@v2  --save-ctc --reference /media/x/be7a23c3-1f3c-4702-97a3-dfff75ed33c3/20201114/x-j.mmi  /media/x/be7a23c3-1f3c-4702-97a3-dfff75ed33c3/20201114/good_reads > /media/x/be7a23c3-1f3c-4702-97a3-dfff75ed33c3/20201114/training/ctc-data/basecalls.sam 
> loading model
> loading reference
> calling: 0 reads [00:00, ? reads/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/x/.local/lib/python3.5/site-packages/bonito/multiprocessing.py", line 138, in run
    self.output_queue.put((k, self.func(v)))
  File "/home/x/.local/lib/python3.5/site-packages/bonito/ctc/basecall.py", line 134, in ctc_decoder
    return {'chunks': chunks, 'targets': targets, **decode(scores, model.decode)}
  File "/home/x/.local/lib/python3.5/site-packages/bonito/ctc/basecall.py", line 50, in decode
    seq, path = decode(scores['scores'], beamsize=1, qscores=True, return_path=True)
  File "/home/x/.local/lib/python3.5/site-packages/bonito/ctc/model.py", line 40, in decode
    x = x.exp().cpu().numpy().astype(np.float32)
AttributeError: 'numpy.ndarray' object has no attribute 'exp'

```

**Comment by iiSeymour** [comment]
That looks like an issue I fixed 2 days with https://github.com/nanoporetech/bonito/commit/c1ae23b3ddbe269965d49869615f41247a71e003 does git log show you are on https://github.com/nanoporetech/bonito/commit/2c51ec5a68f77be15c4f915997f7de575fcb1a6d?


```
$ git log -n 1
commit 2c51ec5a68f77be15c4f915997f7de575fcb1a6d
Author: Chris Seymour <christopher.seymour@nanoporetech.com>
Date:   Fri Nov 13 15:02:00 2020 +0000

    recursive fast5 discovery support
```

I see the from the paths in the traceback that the package is getting picked up from a user install _(`/home/x/.local/`)_ so it could be that you are picking up `ont-bonito==0.3.0` that you installed with `pip` and not the checked out version. Can you either remove the user install of `ont-bonito` and rerun `python setup.py develop` or try with a virtualenv?

**Comment by mattdmem** [comment]
Hmm odd as I installed it in a conda env... will have a play around and see if I can get it working. Thanks for your help!

**Comment by mattdmem** [comment]
ok running now! thanks again
