### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by mattdmem** [nanoporetech/bonito#67]
Training failed with the following error

````
 bonito train  --directory /media/x/be7a23c3-1f3c-4702-97a3-dfff75ed33c3/20201114/training/ctc-data /media/x/be7a23c3-1f3c-4702-97a3-dfff75ed33c3/20201114/training/model-data -f --batch 50
````

```
[loading data]
[loading model]
[145677/145677]: 100%|########################################################| [39:32, loss=0.0293]
Traceback (most recent call last):
  File "/home/x/.local/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/home/x/.local/lib/python3.5/site-packages/bonito/__init__.py", line 39, in main
    args.func(args)
  File "/home/x/.local/lib/python3.5/site-packages/bonito/cli/train.py", line 84, in main
    model, device, test_loader, criterion=criterion
  File "/home/x/.local/lib/python3.5/site-packages/bonito/training.py", line 212, in test
    accuracy_with_cov(ref, seq) if len(seq) else 0. for ref, seq in zip(refs, seqs)
  File "/home/x/.local/lib/python3.5/site-packages/bonito/training.py", line 212, in <listcomp>
    accuracy_with_cov(ref, seq) if len(seq) else 0. for ref, seq in zip(refs, seqs)
  File "/home/x/.local/lib/python3.5/site-packages/bonito/training.py", line 199, in <lambda>
    accuracy_with_cov = lambda ref, seq: accuracy(ref, seq, min_coverage=min_coverage)
  File "/home/x/.local/lib/python3.5/site-packages/bonito/util.py", line 343, in accuracy
    _, cigar = parasail_to_sam(alignment, seq)
  File "/home/x/.local/lib/python3.5/site-packages/bonito/util.py", line 316, in parasail_to_sam
    first_count, first_op = first.groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by chAwater** [comment]
I encountered the same error. I think it is a bug.
It seems like that the model predicted results are not matched/aligned to the target sequence at all.

A "hotfix" is using a different `--seed` in `bonito train`, and pray.
