### ISSUE TITLE
model evaluation & download training data fails - memory issue

### ISSUE THREAD

**Issue by mattdmem** [nanoporetech/bonito#73]
I want to evaluate a model I trained...even though I can use the model in basecalling I can't seem to evaluate it:

```
 bonito evaluate  /media/x/be7a23c3-1f3c-4702-97a3-dfff75ed33c3/20201114/training/model-data

* loading data
Traceback (most recent call last):
  File "/home/x/miniconda3/envs/nanopore/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito', 'console_scripts', 'bonito')()
  File "/home/x/miniconda3/envs/nanopore/lib/python3.7/site-packages/bonito/__init__.py", line 39, in main
    args.func(args)
  File "/home/x/miniconda3/envs/nanopore/lib/python3.7/site-packages/bonito/cli/evaluate.py", line 27, in main
    directory=args.directory, validation=True
  File "/home/x/miniconda3/envs/nanopore/lib/python3.7/site-packages/bonito/util.py", line 223, in load_data
    chunks = np.load(os.path.join(directory, "chunks.npy"))
  File "/home/md1mpar/.local/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/x/miniconda3/envs/nanopore/lib/python3.7/site-packages/bonito/data/dna_r9.4.1/chunks.npy'

```

I thought then it might be that I hadn't downloaded the training data, but having issues with that too:

```
bonito download   --training
[downloading training data]
[downloaded dna_r9.4.1.hdf5]                                                                        
[converting dna_r9.4.1.hdf5]
> preparing training chunks

1250345it [01:11, 17371.60it/s]
Traceback (most recent call last):
  File "/home/x/miniconda3/envs/nanopore/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito', 'console_scripts', 'bonito')()
  File "/home/x/miniconda3/envs/nanopore/lib/python3.7/site-packages/bonito/__init__.py", line 39, in main
    args.func(args)
  File "/home/x/miniconda3/envs/nanopore/lib/python3.7/site-packages/bonito/cli/download.py", line 103, in main
    File(__models__, train, args.force).download()
  File "/home/x/miniconda3/envs/nanopore/lib/python3.7/site-packages/bonito/cli/download.py", line 76, in download
    convert(args)
  File "/home/x/miniconda3/envs/nanopore/lib/python3.7/site-packages/bonito/cli/convert.py", line 118, in main
    training_chunks = filter_chunks(training_chunks)
  File "/home/x/miniconda3/envs/nanopore/lib/python3.7/site-packages/bonito/cli/convert.py", line 91, in filter_chunks
    filtered = select_indices(chunks, idx)
  File "/home/x/miniconda3/envs/nanopore/lib/python3.7/site-packages/bonito/cli/convert.py", line 82, in select_indices
    ds.chunks.squeeze(1)[idx], ds.targets[idx], ds.lengths[idx]
MemoryError: Unable to allocate 16.4 GiB for an array with shape (1221470, 3600) and data type float32
```

Any help appreciated!! Thanks!

**Comment by iiSeymour** [comment]
Hey @mattdmem 

You already have your own training data so just use `--directory` to tell `bonito evaluate` where to find it -

```
$ bonito evaluate --directory .../20201114/training/training-data .../20201114/training/model-data
```

Note: You won't want evaluate on the same set of chunks you trained on so best to hold out reads for this purpose.

For the second issue - the downloaded training data is chunked into training examples after the download and it's all done in memory *(and unfortunately does required more than 16GB of RAM - 1,221,470 chunks by 3600 samples in FP32 is ~= 17.5GB)*.
