### ISSUE TITLE
Bonito gets stuck

### ISSUE THREAD

**Issue by dominik-handler** [nanoporetech/bonito#79]
Hi,

I am trying to use Bonito as a Singularity image and it works mostly fine. 
Sometimes I get these errors and in this case it is very reproducible. Do you have any idea what the problem might be here? The caller also does not terminate but the CPU and GPU tasks hang without any activity. 

Can it be that Bonito has problem with multi-read fast5 files that have been generated by aggregating single-read fast5 files using the ONT single_to_multi_fast5 tool? 

```
R9.4_RAD002_wtOSC_DNA_SambrooksDNA/basicNanopore/BONITO/raw-fast5/4/ > text_1.fasta
> loading model
> calling: 0 reads [00:00, ? reads/s]Exception in thread Thread-1:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/bonito/fast5.py", line 113, in get_raw_data_for_read
    return Read(f5_fh.get_read(read_id), filename)
  File "/usr/local/lib/python3.6/dist-packages/bonito/fast5.py", line 22, in __init__
    self.run_id = read.get_run_id().decode()
AttributeError: 'str' object has no attribute 'decode'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/bonito/multiprocessing.py", line 181, in run
    for (k, v) in self.iterator:
  File "/usr/local/lib/python3.6/dist-packages/bonito/crf/basecall.py", line 105, in <genexpr>
    stitched = ((read, _stitch(x)) for (read, x) in unbatchify(batches))
  File "/usr/local/lib/python3.6/dist-packages/bonito/util.py", line 208, in <genexpr>
    (k, concat([v for (k, v) in group], dim))
  File "/usr/local/lib/python3.6/dist-packages/bonito/util.py", line 203, in <genexpr>
    (k, select_range(v, start, end, dim))
  File "/usr/local/lib/python3.6/dist-packages/bonito/crf/basecall.py", line 102, in <genexpr>
    (read, quantise_int8(compute_scores(model, batch)))
  File "/usr/local/lib/python3.6/dist-packages/bonito/util.py", line 181, in batchify
    for k, v in items:
  File "/usr/local/lib/python3.6/dist-packages/bonito/crf/basecall.py", line 99, in <genexpr>
    ((read, chunk(signal, chunksize, overlap, pad_start=True)) for (read, signal) in reads)
  File "/usr/local/lib/python3.6/dist-packages/bonito/crf/basecall.py", line 95, in <genexpr>
    ((read, i), x) for read in reads
  File "/usr/local/lib/python3.6/dist-packages/bonito/fast5.py", line 124, in get_reads
    for read in pool.imap(get_raw_data_for_read, job):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
AttributeError: 'str' object has no attribute 'decode'
```

Thank you,
Dominik

**Comment by dominik-handler** [comment]
After some testing it seems that the error is related to the dataset. Only my oldest 3 sequencing runs show this behavior. Therefore I also think it is unrelated to single_to_multi_fast5 as also some of my other runs have been aggregated using it.

**Comment by iiSeymour** [comment]
It's failing on extracting the run id for these older reads - a byte string is expected but you are getting a string *(I'm guessing an empty string?)*

A simple fix if you want recall this data is change `self.run_id = read.get_run_id().decode()` to `self.run_id = "my_run_id"` [here](https://github.com/nanoporetech/bonito/blob/master/bonito/fast5.py#L22).

**Comment by dominik-handler** [comment]
Thank you for your suggestion. I was finally able to test it. Unfortunately it did not fix the problem. I am still getting the very same problem:
```
> loading model
> calling: 0 reads [00:00, ? reads/s]Exception in thread Thread-1:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/bonito/bonito/fast5.py", line 140, in get_raw_data_for_read
    return Read(f5_fh.get_read(read_id), filename)
  File "/bonito/bonito/fast5.py", line 32, in __init__
    self.channel = channel_info['channel_number'].decode()
AttributeError: 'str' object has no attribute 'decode'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/bonito/bonito/multiprocessing.py", line 67, in run
    for item in self.iterator:
  File "/bonito/bonito/util.py", line 181, in batchify
    for k, v in items:
  File "/bonito/bonito/crf/basecall.py", line 99, in <genexpr>
    ((read, chunk(signal, chunksize, overlap, pad_start=True)) for (read, signal) in reads)
  File "/bonito/bonito/crf/basecall.py", line 95, in <genexpr>
    ((read, i), x) for read in reads
  File "/bonito/bonito/fast5.py", line 151, in get_reads
    for read in pool.imap(get_raw_data_for_read, job):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
AttributeError: 'str' object has no attribute 'decode'
```
Any other suggestion or would it help you the have access to a fast5 file?

**Comment by iiSeymour** [comment]
Yes, it would help to have access to a file - if you could upload one [here](https://nanoporetech.ent.box.com/f/7c4375e2b71b48258ebed29f198b89ab) I'll get you a patch sorted.

**Comment by dominik-handler** [comment]
Hi, 

file is uplodaded.

**Comment by iiSeymour** [comment]
I was able to successfully basecall the updated reads with `v0.3.5`

**Comment by ktan8** [comment]
I'm facing a similar issue with bonito v0.3.5. As highlighted above, it seems that this issue is present mainly in the older fast5 dataset.

It seems that the earlier versions of the raw fast5 files do not have the 'self.run_id' and 'self.channel' fields, therefore raising the errors above. I was however able to get bonito to basecall these older reads by hardcoding these two fields in my "fast5.py" file as Seymour recommended above.

However, it feels a bit hackish since I now need to maintain two versions of the "fast5.py" file, and switch them around which is a little bit annoying. I'm guessing a better fix would be to update these older fast5 files with a "run_id" and "channel_id"? Or Bonito can be designed to be fault tolerant towards these older fast5 files in the future?
