### ISSUE TITLE
Error trying to download latest basecalling models

### ISSUE THREAD

**Issue by drdna** [nanoporetech/bonito#99]
(venv3) [user@login002 bonito]$ bonito download --models --latest
[downloading models]
[skipping dna_r9.4.1.zip]
Traceback (most recent call last):
  File "/project/user_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/project/user_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/project/user_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/user_uksr/bonito/venv3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/project/user_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/project/user_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/project/user_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/project/user_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/project/user_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/project/user_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/user_uksr/bonito/venv3/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito', 'console_scripts', 'bonito')()
  File "/project/user_uksr/bonito/bonito/__init__.py", line 39, in main
    args.func(args)
  File "/project/user_uksr/bonito/bonito/cli/download.py", line 106, in main
    File(__models__, model, args.force).download()
  File "/project/user_uksr/bonito/bonito/cli/download.py", line 42, in download
    req = requests.get(self.url, stream=True)
  File "/project/user_uksr/bonito/venv3/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/project/user_uksr/bonito/venv3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/project/user_uksr/bonito/venv3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/project/user_uksr/bonito/venv3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/project/user_uksr/bonito/venv3/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by iiSeymour** [comment]
Hey @drdna 

The model hosting seems okay from here - it's possible there was a blip and the service was down when you tried.

```
$ bonito download --models --latest
[downloading models]
[downloaded dna_r9.4.1.zip]                                                                         
[downloaded dna_r10.3.zip] 
```

Do you see this repeatedly or know if your network has any restrictions?

**Comment by drdna** [comment]
Installation steps:

git clone https://github.com/nanoporetech/bonito.git
cd bonito
python3 -m venv venv3
source venv3/bin/activate
pip install --upgrade pip
pip install -r requirements.txt 
python setup.py develop
bonito download --models —latest

Same error:

(venv3) (base) [farman@login004 bonito]$ bonito download --models --latest
[downloading models]
Traceback (most recent call last):
  File "/project/farman_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/project/farman_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/project/farman_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/farman_uksr/bonito/venv3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/project/farman_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/project/farman_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/project/farman_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/project/farman_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/project/farman_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/project/farman_uksr/bonito/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/ohpc/pub/libs/Miniconda3/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/farman_uksr/bonito/venv3/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito', 'console_scripts', 'bonito')()
  File "/project/farman_uksr/bonito/bonito/__init__.py", line 39, in main
    args.func(args)
  File "/project/farman_uksr/bonito/bonito/cli/download.py", line 104, in main
    File(__models__, model, args.force).download()
  File "/project/farman_uksr/bonito/bonito/cli/download.py", line 42, in download
    req = requests.get(self.url, stream=True)
  File "/project/farman_uksr/bonito/venv3/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/project/farman_uksr/bonito/venv3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/project/farman_uksr/bonito/venv3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/project/farman_uksr/bonito/venv3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/project/farman_uksr/bonito/venv3/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
> On Dec 30, 2020, at 6:19 AM, Chris Seymour <notifications@github.com> wrote:
> 
> CAUTION: External Sender
> 
> 
> Hey @drdna <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdrdna&data=04%7C01%7Cmark.farman%40uky.edu%7Cb60237066f9f47747e5908d8acb4ba2a%7C2b30530b69b64457b818481cb53d42ae%7C0%7C0%7C637449239502229251%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O9QfPDvWwIQbveeAQBj%2BXhIXYKo7IWlo8XTnc3xuliA%3D&reserved=0>
> The model hosting seems okay from here - it's possible there was a blip and the service was down when you tried.
> 
> $ bonito download --models --latest
> [downloading models]
> [downloaded dna_r9.4.1.zip]                                                                         
> [downloaded dna_r10.3.zip] 
> Do you see this repeatedly or know if your network has any restrictions?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnanoporetech%2Fbonito%2Fissues%2F99%23issuecomment-752423585&data=04%7C01%7Cmark.farman%40uky.edu%7Cb60237066f9f47747e5908d8acb4ba2a%7C2b30530b69b64457b818481cb53d42ae%7C0%7C0%7C637449239502239246%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BgGK%2FZ%2F5WCCuC1FilxAtv27UjAaa9l7FCdczN5Uw3yk%3D&reserved=0>, or unsubscribe <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAYUUDM2M3ZHDOEGCSG2AR3SXMECZANCNFSM4VMYMEVQ&data=04%7C01%7Cmark.farman%40uky.edu%7Cb60237066f9f47747e5908d8acb4ba2a%7C2b30530b69b64457b818481cb53d42ae%7C0%7C0%7C637449239502239246%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4186YFs8tQ58BVoWx54s44No4Zyd5MGFt1nBsuGLuR8%3D&reserved=0>.
> 



Mark L. Farman 
Professor, Department of Plant Pathology
225 Plant Science Building
1405 Veteran's Dr.
University of Kentucky
Lexington, KY 40546 USA 
tel: 	(859) 218-0728 
fax: 	(859) 323-1961

**Comment by drdna** [comment]
It looks like there was some kind of cryptic download restriction - even though I routinely transfer data to/from that node. I logged in to a data transfer node instead and it worked fine.

Thanks.

**Comment by iiSeymour** [comment]
Good to hear you managed to resolve this using a data transfer node- let me know if you run into further issues.
